### PR TITLE
Candy Brick Game

### LINKED ISSUE #1144: Candy Brick Game
**Project title**

Candy Brick Game

**Project Description**

Candy Brick Game

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

### PR DESCRIPTION
**Pull request by AnIkeT126**
<hr>

## Description 📜

A candy brick game based on the simple concept of candy crush.

Fixes #1144 
<hr>

## Type of change 📝

Please delete options that are not relevant. And in order to tick the check box just put x inside them for example [x] like this

- [x] Add a new project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant. And in order to tick the check box just put x inside them for example [x] like this

- [x] Project using HTML, CSS & JS

<hr>
 
## Checklist ✅

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Recommended) 📸

https://user-images.githubusercontent.com/82095877/166493945-0f749395-5f76-4f16-bfe3-388ad50a3ee5.mp4

### CODE REVIEW

**Comment by AnIkeT126** [comment]
@gurjeetsinghvirdee  @amyra98 please review this PR, and merge it upon finding it correct

**Comment by gurjeetsinghvirdee** [comment]
@AnIkeT126 Title video ke sth match ni kr ra

**Comment by AnIkeT126** [comment]
ha wo saati files ek jaagh, toh glt drag and drop ho gyi, updating

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Comment by AnIkeT126** [comment]
Bhai yeh bhi level 2🥲🥲

**Comment by AnIkeT126** [comment]
> > Bhai yeh bhi level 2🥲🥲
> 
> responsiveness Bhai , I think galat repo m mentor hu labels do toh sawal uth jaate h😶‍🌫️ chor bhi ni skta fir ye repo bhi inactive hojygi


Are nhi nhi.... Pls chhodna mt
Ab saari pr responsive deta hu
Isko ek aur pr mei responsive kr du??

**Comment by gurjeetsinghvirdee** [comment]
> > > Bhai yeh bhi level 2🥲🥲
> > 
> > 
> > responsiveness Bhai , I think galat repo m mentor hu labels do toh sawal uth jaate h😶‍🌫️ chor bhi ni skta fir ye repo bhi inactive hojygi
> 
> Are nhi nhi.... Pls chhodna mt Ab saari pr responsive deta hu Isko ek aur pr mei responsive kr du??

as a Ui chng krke or resposnive krdega toh level2 aajyga

**Comment by AnIkeT126** [comment]
> > > > Bhai yeh bhi level 2🥲🥲
> > > 
> > > 
> > > responsiveness Bhai , I think galat repo m mentor hu labels do toh sawal uth jaate h😶‍🌫️ chor bhi ni skta fir ye repo bhi inactive hojygi
> > 
> > 
> > Are nhi nhi.... Pls chhodna mt Ab saari pr responsive deta hu Isko ek aur pr mei responsive kr du??
> 
> as a Ui chng krke or resposnive krdega toh level2 aajyga

ok bhjeta hu PR ek aur

**Pull request merged**
