### PR TITLE
Fluid website

### PR DESCRIPTION
**Pull request by Avik-creator**
Worked On Issue Number: #1270 
Issue Name: Fluid Website.
Issue Type: Feature Added.

- [x] I'm GSSoC'22 contributor

Picture of the Project:
Screenshot 2022-05-06 at 4 23 38 PM
- Not to be exact.

Video Of the Project:
https://user-images.githubusercontent.com/77090462/167177001-20735063-e7b6-4b94-b42a-16462bfc2836.mov

### CODE REVIEW

**Comment by Avik-creator** [comment]
@gurjeetsinghvirdee @khushi-purwar Please check and review it.

**Comment by gurjeetsinghvirdee** [comment]
Attach video @Avik-creator

**Comment by Avik-creator** [comment]
I have added video in readme sir @gurjeetsinghvirdee

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Comment by gurjeetsinghvirdee** [comment]
copied from here https://www.youtube.com/watch?v=CZTCciHE72I&list=WL&index=1

**Pull request merged**
