### PR TITLE
Image pixel effect

### LINKED ISSUE #1667: Particle-falling. -effect by vanilla js
**Project title**
Particles falling effect by vanilla js

**Project Description**
Any base64 image can be converted into small small particle and it will create particle falling effect on the image.

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

### PR DESCRIPTION
**Pull request by mayank-del**
<hr>

## Description 📜
It is effect using Basic math functions of vanilla javascript to play with the pixels of images

Fixes #1667 

<hr>

## Type of change 📝

Please delete options that are not relevant. In order to tick the check box just put x inside them for example [x] like this

- [x] Add a new project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant. In order to tick the check box just put x inside them for example [x] like this

- [x] Project using HTML, CSS & JS

<hr>
 
## Checklist ✅

Please delete options that are not relevant. In order to tick the check box just put x inside them for example [x] like this

- [] I have performed a self-review of my own code or work.
- [] I have commented on my code, particularly in hard-to-understand areas.
- [] My changes generate no new warnings.
- [] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Recommended) 📸

pixel

### CODE REVIEW

**Comment by mayank-del** [comment]
@Gurdeep475 , @Mrjoy832 , please check and merge, else seven day will be over and bot will close the issue.

**Comment by Mrjoy832** [comment]
> @Gurdeep475 , @Mrjoy832 , please check and merge, else seven day will be over and bot will close the issue.

bot se upor hum hain😂😂re-open kor denge..aur merge hoga sab time de do thora...mera aur vi project hain

**Comment by Mrjoy832** [comment]
image
Whats this? changes should be done only on your folder

**Comment by mayank-del** [comment]
Can you tell me

> image Whats this? changes should be done only on your folder

@Mrjoy832  sir, can you tell me one thing, If I have to push multiple projects in one repo, all the previous changes  comes on the branch which comes after that even after I make a new branch , it happens , what should I do?

**Comment by Mrjoy832** [comment]
> Can you tell me
> 
> > image Whats this? changes should be done only on your folder
> 
> @Mrjoy832 sir, can you tell me one thing, If I have to push multiple projects in one repo, all the previous changes comes on the branch which comes after that even after I make a new branch , it happens , what should I do?

You can delete previous branch after merging of PR and can create every new PR for Every new issue

**Comment by mayank-del** [comment]
@Mrjoy832 ,sir ,please remove invalid tag , i have deleted every unnecessary files from this pr

**Comment by mayank-del** [comment]
Now @Mrjoy832  merge this pr , 
wo copy/pasting ke time ek do curly braces ek line niche ho gyaa hai purane todo app me, wohi change aa raha , apka todo app , maine dubara se add kar diya hai successfully.

**Comment by mayank-del** [comment]
> Now @Mrjoy832 merge this pr , wo copy/pasting ke time ek do curly braces ek line niche ho gyaa hai purane todo app me, wohi change aa raha , apka todo app , maine dubara se add kar diya hai successfully.
> 

> @Mrjoy832 same as cute bear login

**Comment by mayank-del** [comment]
@Mrjoy832 ,hum bass jo dusre PR ke pages the , unko delete kiye hain wo isme aa rhe the

**Comment by mayank-del** [comment]
> > > Now @Mrjoy832 merge this pr , wo copy/pasting ke time ek do curly braces ek line niche ho gyaa hai purane todo app me, wohi change aa raha , apka todo app , maine dubara se add kar diya hai successfully.
> > 
> > 
> > > @Mrjoy832 same as cute bear login
> 
> image

@Mrjoy832 ,hum bass jo dusre PR ke pages the , unko delete kiye hain wo isme aa rhe the

**Pull request closed without merging**
