### PR TITLE
Filter Fun

### PR DESCRIPTION
**Pull request by AnIkeT126**
<hr>

## Description 📜

A web app taking its base from openCV concepts like, hsv filet rgb2gray, average filets, Gaussian filters and more to apply filter to images when uploaded.

Fixes #<issue_number_here>

<hr>

## Type of change 📝

Please delete options that are not relevant. And in order to tick the check box just put x inside them for example [x] like this

- [x] Add a new project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant. And in order to tick the check box just put x inside them for example [x] like this

- [x] Project using HTML, CSS & JS

<hr>
 
## Checklist ✅

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Recommended) 📸

https://user-images.githubusercontent.com/82095877/166000404-628b976f-52b0-422c-bc13-2e283f5d5bfb.mp4

### CODE REVIEW

**Comment by AnIkeT126** [comment]
@gurjeetsinghvirdee please review this PR, and the video is in this format, because screen recording could not capture the shifted page while taking image.

**Comment by gurjeetsinghvirdee** [comment]
fetch upstream @AnIkeT126

**Comment by AnIkeT126** [comment]
> fetch upstream @AnIkeT126

Fetched.

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Comment by AnIkeT126** [comment]
> ## Description 📜
> A web app taking its base from openCV concepts like, hsv filet rgb2gray, average filets, Gaussian filters and more to apply filter to images when uploaded.
> 
> Fixes #1047 
> 
> ## Type of change 📝
> Please delete options that are not relevant. And in order to tick the check box just put x inside them for example [x] like this
> 
> * [x]  Add a new project
> 
> ## Domain of Contribution 📊
> Please delete options that are not relevant. And in order to tick the check box just put x inside them for example [x] like this
> 
> * [x]  Project using HTML, CSS & JS
> 
> ## Checklist ✅
> Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this
> 
> * [x]  I have performed a self-review of my own code or work.
> * [x]  I have commented on my code, particularly in hard-to-understand areas.
> * [x]  My changes generates no new warnings.
> * [x]  I'm GSSoC'22 contributor
> 
> ## Screenshots / Gif (Recommended) 📸
>  video.mp4

**Comment by gurjeetsinghvirdee** [comment]
> > ## Description 📜
> > A web app taking its base from openCV concepts like, hsv filet rgb2gray, average filets, Gaussian filters and more to apply filter to images when uploaded.
> > Fixes #1047
> > ## Type of change 📝
> > Please delete options that are not relevant. And in order to tick the check box just put x inside them for example [x] like this
> > 
> > * [x]   Add a new project
> > 
> > ## Domain of Contribution 📊
> > Please delete options that are not relevant. And in order to tick the check box just put x inside them for example [x] like this
> > 
> > * [x]   Project using HTML, CSS & JS
> > 
> > ## Checklist ✅
> > Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this
> > 
> > * [x]   I have performed a self-review of my own code or work.
> > * [x]   I have commented on my code, particularly in hard-to-understand areas.
> > * [x]   My changes generates no new warnings.
> > * [x]   I'm GSSoC'22 contributor
> > 
> > ## Screenshots / Gif (Recommended) 📸
> > video.mp4

?

**Comment by AnIkeT126** [comment]
> > > ## Description 📜
> > > A web app taking its base from openCV concepts like, hsv filet rgb2gray, average filets, Gaussian filters and more to apply filter to images when uploaded.
> > > Fixes #1047
> > > ## Type of change 📝
> > > Please delete options that are not relevant. And in order to tick the check box just put x inside them for example [x] like this
> > > 
> > > * [x]    Add a new project
> > > 
> > > ## Domain of Contribution 📊
> > > Please delete options that are not relevant. And in order to tick the check box just put x inside them for example [x] like this
> > > 
> > > * [x]    Project using HTML, CSS & JS
> > > 
> > > ## Checklist ✅
> > > Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this
> > > 
> > > * [x]    I have performed a self-review of my own code or work.
> > > * [x]    I have commented on my code, particularly in hard-to-understand areas.
> > > * [x]    My changes generates no new warnings.
> > > * [x]    I'm GSSoC'22 contributor
> > > 
> > > ## Screenshots / Gif (Recommended) 📸
> > > video.mp4
> 
> ?

by  mistake bhai..nvm

**Pull request merged**
