### PR TITLE
Adding Todo App

### PR DESCRIPTION
**Pull request by abaran803**
This PR is regarding issue #9

### CODE REVIEW

**Comment by khushi-purwar** [comment]
@abaran803 add the readme file.

**Comment by abaran803** [comment]
> @abaran803 add the readme file.

@khushi-purwar I have added the readme file, please check it.

**Comment by khushi-purwar** [comment]
Correct the project title in readme file.

**Comment by abaran803** [comment]
> Correct the project title in readme file.

I have corrected the title of readme file

**Pull request merged**
