### PR TITLE
adding fortune cookie generator

### LINKED ISSUE #839: Fortune Cookie Generator
**Project title**

Fortune Cookie Generator

**Project Description**

A web-app based fully responsive Fortune Cookie Generator.

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

### PR DESCRIPTION
**Pull request by AnIkeT126**
<hr>

A web-app based fully responsive Fortune Cookie Generator.

 

Fixes #839 

<hr>

## Type of change 📝

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Add a new project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Project using HTML, CSS & JS

<hr>
 
## Checklist ✅

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Optional) 📸

image
image

### CODE REVIEW

**Comment by AnIkeT126** [comment]
please merge this PR, upon reviewing it.

**Comment by AnIkeT126** [comment]
@khushi-purwar please review this PR, and merge it upon finding it correct, this is a responsive page with a fine UI, so please add a level label accordingly

**Comment by abhilipsasahoo03** [comment]
Hi @khushi-purwar I would like to let you know that this project has been plagiarized from the Fortune Cookie generator project I submitted to Arpit Jain's Amazing Js Projects. Here is the link: https://github.com/arpit456jain/Amazing-Js-Projects/pull/447
You can compare the code, the layout is also the same.

**Comment by Suvraneel** [comment]
@khushi-purwar  @meinhoonharsh 
`Do not merge`

A git blame or diff shows plagiarism above >95%

**Pull request closed without merging**
