### PR TITLE
text speed controller

### LINKED ISSUE #722: Text-Speed-controller
**Project title**

Text-Speed-controller

**Project Description**

A web-app based Text-Speed-controller

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

### PR DESCRIPTION
**Pull request by AnIkeT126**
<hr>

A web app text speed controller

Fixes #722 

<hr>

## Type of change 📝

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Add a new project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Project using HTML, CSS & JS

<hr>
 
## Checklist ✅

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Optional) 📸

image

### CODE REVIEW

**Comment by AnIkeT126** [comment]
@khushi-purwar please merge this PR, upon reviewing it.

**Comment by AnIkeT126** [comment]
@khushi-purwar please merge this PR, upon reviewing it.

**Comment by AnIkeT126** [comment]
@khushi-purwar Can you please review this PR and merge it upon finding it correct.

**Review by gurjeetsinghvirdee — APPROVED** [review]
Good to go

**Comment by AnIkeT126** [comment]
@gurjeetsinghvirdee when I was assigned this issue i was given a level label 3 as my other issues and PR, it seems that you have removed those to ass new, please understand that we worked on these issues considering the amount of points we were getting, so please restore my old level lables in all the PRs because I started working on them post the level label was addressed

**Comment by gurjeetsinghvirdee** [comment]
Buddy things were changed from yesterday, so no one gives you level3 labels on small projects

For level3
Project works smoothly
Mobile responsive
UI look good

But in mini projects I can't give you more than level2
It's just a simple project 

I know why you created 8PRs in just one day bcoz this pA don't look out codes don't even judge just put level3 without seeing, but now I'm mentor I will judge even check If I found copy paste I will male a list and gave to PM then whether you want to report you can do it

**Review by khushi-purwar — APPROVED** [review]

**Comment by AnIkeT126** [comment]
> Buddy things were changed from yesterday, so no one gives you level3 labels on small projects
> 
> For level3 Project works smoothly Mobile responsive UI look good
> 
> I know why you created 8PRs in just one day bcoz this pA don't look out codes don't even judge just put level3 without seeing, but now I'm mentor I will judge even check If I found copy paste I will make a list and gave to PM or post publically like a poll something Like it was a level3 level project or not If you wanna complain it then do it, I don't have issues

The problem only being that this wasn't informed to us on the official GSSoC server, and the measures were taken directly.
So as a contributor I am ought to seek answers, please don't find it rude, but that's how we should roll i guess.

**Pull request merged**
