### PR TITLE
adding election map

### LINKED ISSUE #900: Election Map
**Project title**

Election Map

**Project Description**

JavaScript code to add two candidates running for president and display the number of votes they received from each state, both in a table on the bottom right and when you mouse over a state, and provide an election map for the same.

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

### PR DESCRIPTION
**Pull request by AnIkeT126**
<hr>

## Description 📜

JavaScript code to add two candidates running for president and display the number of votes they received from each state, both in a table on the bottom right and when you mouse over a state and provide an election map for the same.

Fixes #900 

<hr>

## Type of change 📝

Please delete options that are not relevant. And in order to tick the check box just put x inside them for example [x] like this

- [x] Add a new project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant. And in order to tick the check box just put x inside them for example [x] like this

- [x] Project using HTML, CSS & JS

<hr>
 
## Checklist ✅

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Recommended) 📸

image

### CODE REVIEW

**Comment by AnIkeT126** [comment]
@gurjeetsinghvirdee and @khushi-purwar please review this PR, I have added a working video of it in the readme as per your advice.

**Review by gurjeetsinghvirdee — CHANGES_REQUESTED** [review]
You uploaded a wrong video I think

**Comment by AnIkeT126** [comment]
> You uploaded a wrong video I think

No, @gurjeetsinghvirdee  I think u need to just click on that and It will take you to where the video is hosted, and you can see it there.

**Comment by gurjeetsinghvirdee** [comment]
> > You uploaded a wrong video I think
> 
> No, @gurjeetsinghvirdee I think u need to just click on that and It will take you to where the video is hosted, and you can see it there.

bro video chal toh rhi hai par kisi dusre project ki, check once again

**Comment by AnIkeT126** [comment]
> > > You uploaded a wrong video I think
> > 
> > 
> > No, @gurjeetsinghvirdee I think u need to just click on that and It will take you to where the video is hosted, and you can see it there.
> 
> bro video chal toh rhi hai par kisi dusre project ki, check once again

Change kr diya, glti se is video ka aa gya, abhi check kr lo ek baar  @gurjeetsinghvirdee .

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Pull request merged**
