### PR TITLE
adding captcha generator, resolving issue #702

### LINKED ISSUE #702: Captcha Generator
**Project title**

Captcha Generator

**Project Description**

A web-app-based Captcha Generator.

**Stack**:  

- [x] Html
- [x] CSS
- [x] JavaScript

### PR DESCRIPTION
**Pull request by AnIkeT126**
<hr>

## Description 📜

A web-app-based Captcha Generator.

Fixes #702

<hr>

## Type of change 📝

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Add a new project

## Domain of Contribution 📊

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Project using HTML, CSS & JS

<hr>
 
## Checklist ✅

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Optional) 📸

image

### CODE REVIEW

**Comment by AnIkeT126** [comment]
@khushi-purwar please merge this PR, upon reviewing it.

**Comment by AnIkeT126** [comment]
@khushi-purwar please merge this PR, upon reviewing it.

**Comment by AnIkeT126** [comment]
@khushi-purwar Can you please review this PR and merge it upon finding it correct.

**Review by gurjeetsinghvirdee — CHANGES_REQUESTED** [review]
This branch is 1 commit ahead, 187 commits behind khushi-purwar/WebDev-ProjectKart:master.

**Comment by AnIkeT126** [comment]
> This branch is 1 commit ahead, 187 commits behind khushi-purwar/WebDev-ProjectKart:master.

@khushi-purwar and @gurjeetsinghvirdee This branch is one commit ahead because of its own commit and when I made this PR, the branch was fully fetched and merged.
So please approve this PR, as that is because of the delay in approval and merge

**Comment by AnIkeT126** [comment]
> > This branch is 1 commit ahead, 187 commits behind khushi-purwar/WebDev-ProjectKart:master.
> 
> @khushi-purwar and @gurjeetsinghvirdee This branch is one commit ahead because of its own commit and when I made this PR, the branch was fully fetched and merged. So please approve this PR, as that is because of the delay in approval and merge


@khushi-purwar and @gurjeetsinghvirdee when I was assigned this issue i was given a level label 3 as my other issues and PR, it seems that you have removed those to ass new, please understand that we worked on these issues considering the amount of points we were getting, so please restore my old level lables in all the PRs because I started working on them post the level label was addressed

**Comment by AnIkeT126** [comment]
@khushi-purwar can you review this PR now, and please merge it with its original level label.

**Comment by gurjeetsinghvirdee** [comment]
@AnIkeT126 bro fetch your upstream either it will make conflicts and "The quality of PR decides the level. Labels on issues don't matter."

**Comment by AnIkeT126** [comment]
> @AnIkeT126 bro fetch your upstream either it will make conflicts and "The quality of PR decides the level. Labels on issues don't matter."

@gurjeetsinghvirdee I fetched But i did reset it to the last committed state and I could not send pr without that, wait I Will send a new Pr.

**Pull request closed without merging**
