### PR TITLE
Google Login Page

### LINKED ISSUE #711: Google Login Page
**Project title**
Google Login Page 

**Project Description**
Wanted to add Google Login Page using HTML,CSS

**Stack**:  

- [X] Html
- [X] CSS

### PR DESCRIPTION
**Pull request by Mrjoy832**
<hr>

## Description 📜

Added Google Login Page Clone using HTML,CSS which is responsive in nature.
Fixes #711 

<hr>

## Type of change 📝

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [X] Add a new project

<hr>

## Domain of Contribution 📊

- [X] Project using only HTML & CSS
- [ ] Project using HTML, CSS & JS
- [ ] Project using ReactJs

<hr>
 
## Checklist ✅

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [X] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Optional) 📸

image

### CODE REVIEW

**Review by gurjeetsinghvirdee — APPROVED** [review]
Looks good

**Review by khushi-purwar — APPROVED** [review]

**Comment by khushi-purwar** [comment]
Kindly resolve the conflicts at your end.

**Comment by Mrjoy832** [comment]
> Kindly resolve the conflicts at your end.

@khushi-purwar , resolved...kindly check

**Review by khushi-purwar — APPROVED** [review]

**Comment by khushi-purwar** [comment]
Kindly resolve the conflicts

**Comment by Mrjoy832** [comment]
> > Kindly resolve the conflicts at your end.
> 
> @khushi-purwar , resolved...kindly check

@khushi-purwar  resolved conflict

**Pull request merged**
