### PR TITLE
Added PostMaster website

### LINKED ISSUE #1346: Get and post  request making  website
**Project title**
Postmaster

**Project Description**
This website help us to make get and post request in JSON or custom parameters and give us desired response

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

### PR DESCRIPTION
**Pull request by Areebah03**
*Fixed #1346

<hr>

## Description 📜

This website is used to create get and post request from a URL. We can add JSON request or set custom parameter. We get desired response after submitting. I have used html, css, javascript,  prism.js and prism.css to make this website.

Fixes #1346 

<hr>

## Type of change 📝

- [x] Add a new project

<hr>

## Domain of Contribution 📊

- [x] Project using HTML, CSS & JS

<hr>
 
## Checklist ✅

- [x] I have performed a self-review of my own code or work.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Recommended) 📸
ss1

### Creating GET request from URL
get

### Creating POST request using JSON
post

### Creating POST request using custom parameters
param

### CODE REVIEW

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Comment by gurjeetsinghvirdee** [comment]
https://github.com/ravigithub19/postman-clone copied from here @Mrjoy832

**Comment by Areebah03** [comment]
@gurjeetsinghvirdee I have not copied their content. This pr is itself plagiarised from https://www.youtube.com/watch?v=g0gLojpleAg&list=PLu0W_9lII9ajyk081To1Cbt2eI5913SsL&index=63&t=4557s here. I have taken help fron online and tried to build it on my own

**Comment by gurjeetsinghvirdee** [comment]
> @gurjeetsinghvirdee I have not copied their content. This pr is itself plagiarised from https://www.youtube.com/watch?v=g0gLojpleAg&list=PLu0W_9lII9ajyk081To1Cbt2eI5913SsL&index=63&t=4557s here. I have taken help fron online and tried to build it on my own

Then mention you are taking refrence

**Comment by Areebah03** [comment]
Okay, I will do it surely next time. Thank you.

**Pull request merged**
