### PR TITLE
Added Video Player

### LINKED ISSUE #639: Add Video Player
**Project title**
Music Player

**Project Description**
It will works as a normal video player had different speeds of 2x.5x zoom in window volume controller

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

### PR DESCRIPTION
**Pull request by gurjeetsinghvirdee**
<hr>

## Description 📜

It will works as a normal video player had different speeds of 2x.5x zoom in window volume controller

Fixes #639 

<hr>

## Type of change 📝

Please delete options that are not relevant. And in order to tick the check box just put x inside them for example [x] like this

- [x] Add a new project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant. And in order to tick the check box just put x inside them for example [x] like this

- [x] Project using HTML, CSS & JS

<hr>
 
## Checklist ✅

Please delete options that are not relevant. And in order to tick the check box just put x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Optional) 📸

Screenshot (846)

Screenshot (844)

## Video

https://user-images.githubusercontent.com/73753957/162593173-166d0aa2-478f-4364-8a82-2531b87df62b.mp4

### CODE REVIEW

**Review by khushi-purwar — APPROVED** [review]

**Comment by yash-25log** [comment]
Does this got level3? Why so

**Comment by gurjeetsinghvirdee** [comment]
> Does this got level3? Why so

tab me mentor ni that? sare projects level 3 lag re the

**Comment by yash-25log** [comment]
I got late then😅😂

**Comment by gurjeetsinghvirdee** [comment]
> I got late then😅😂

Hn keh skte h

**Pull request merged**
