### PR TITLE
Football Club Website 

### LINKED ISSUE #674: FootBall Club Website
**Project title**
FootBall Club Website
**Project Description**
A front-end website for MAnchester United FootBall Club
**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS

https://leafy-crumble-33f5b9.netlify.app/

### PR DESCRIPTION
**Pull request by RajAdwaita**
<hr>

## Description 📜

Added a new frontend website template.
Fixes #674 

<hr>

## Type of change 📝

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Add a new project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Project using only HTML & CSS

<hr>
 
## Checklist ✅

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Optional) 📸

Add the screenshot of the changes you have made

https://leafy-crumble-33f5b9.netlify.app/

### CODE REVIEW

**Comment by RajAdwaita** [comment]
Hey @khushi-purwar I have done the required changes. Could you please review it once

**Comment by RajAdwaita** [comment]
Now this PR has only one single project file

**Comment by RajAdwaita** [comment]
If this doesn't work please tell me I will make a new PR

**Review by gurjeetsinghvirdee — APPROVED** [review]
LGTM

**Review by khushi-purwar — APPROVED** [review]

**Pull request merged**
