### PR TITLE
Added DnD Dashboard Clone code to the repo!

### LINKED ISSUE #316: I want to add a simple react project which is a clone of Trello/Kanban board
**Project title**
A simple Trello clone using react dnd

**Project Description**
A Kanban board using React.js and react-dnd lib.

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x ] Html
- [x ] CSS
- [x ] JavaScript
- [x ] ReactJS

### PR DESCRIPTION
**Pull request by TANYA-CHAN**
<hr>
## Description 📜
Changes made: Added a file that contains a Trello/Kanban Dashboard clone in React.js using react-dnd lib.
The issue I opened and fixed: I want to add a simple react project which is a clone of Trello/Kanban board #316 

Fixes #316
<hr>

## Type of change 📝
- [x] Add a new project
<hr>

## Domain of Contribution 📊
- [x] Project using HTML, CSS & JS
- [x] Project using ReactJs
<hr>

## Checklist ✅
- [x] My changes generates no new warnings.
- [x] I'm GSSoC'22 contributor
<hr>

## Screenshots / Gif (Optional) 📸
Screenshots have been added to the Readme file of the DnD-Dashboard Project.

### CODE REVIEW

**Comment by khushi-purwar** [comment]
Files are not pushing properly.

**Review by meinhoonharsh — CHANGES_REQUESTED** [review]
you need to add files commit changes before raising PR

**Comment by gurjeetsinghvirdee** [comment]
No response from contributor side so I'm closing this PR

**Comment by TANYA-CHAN** [comment]
I will try again, I don't know why files are not being added properly

**Comment by gurjeetsinghvirdee** [comment]
> I'll try again, I don't know why files are not being added properly :(

You can re add here or make a new PR

**Comment by TANYA-CHAN** [comment]
Because of exams I haven't been able to dedicate time but can I make a new PR when I add files?

**Comment by gurjeetsinghvirdee** [comment]
@TANYA-CHAN ok make a new PR!! first fetch your branch

**Comment by TANYA-CHAN** [comment]
Hey, so I created a local fork and added my project to my local fork, please help me push it to the main rep here. I don't want it to be a mess like last time. @gurjeetsinghvirdee

**Comment by gurjeetsinghvirdee** [comment]
> Hey, so I created a local fork and added my project to my local fork, please help me push it to the main rep here. I don't want it to be a mess like last time. @gurjeetsinghvirdee I have created a new PR, added 20 files once again, hopefully everything should be fine this time. Thank You. 

Clone your fork repo 
Then push your changes

**Comment by TANYA-CHAN** [comment]
I did clone and then push changes, Can you please check and merge?

**Pull request closed without merging**
