### PR TITLE
Hulu UI Clone 

### LINKED ISSUE #600: HULU WebPage Clone
**Project title**
HULU Clone using HTML,CSS,JS

**Project Description**
It's a clone of HULU Webpage using HTML,CSS,JS

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [X] Html
- [X] CSS
- [X] JavaScript

### PR DESCRIPTION
**Pull request by Mrjoy832**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. 

Fixes #600 

<hr>

## Type of change 📝
- Created Hulu UI Clone  using HTML,CSS,JS
- Video Demo is in readme file.
Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [X] Add a new project
- [ ] Modified or enhanced the existing projects
- [ ] Improve the readme of any project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [ ] Project using only HTML & CSS
- [X] Project using HTML, CSS & JS
- [ ] Project using ReactJs

<hr>
 
## Checklist ✅

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Optional) 📸
image

image

### CODE REVIEW

**Comment by Mrjoy832** [comment]
@khushi-purwar , Please check it.

**Comment by khushi-purwar** [comment]
Kindly resolve the conflicts

**Comment by Mrjoy832** [comment]
@khushi-purwar , resolved Branch Conflict

**Review by gurjeetsinghvirdee — CHANGES_REQUESTED** [review]
bro, there is nothing in this file, plz add your changes

**Review by gurjeetsinghvirdee — APPROVED** [review]
LGTM

**Pull request merged**
