### PR TITLE
Myntra Clone

### LINKED ISSUE #1688: Myntra Clone
**Project title**
Myntra Clone

**Project Description**
I want to add a project of myntra clone with proper code files and readme.

**Stack**:  

- [x] Html
- [x] CSS
- [x] JavaScript

### PR DESCRIPTION
**Pull request by i-am-aisha**
<hr>

## Description 📜
I create a  full responsive Myntra Clone with all functionality. 

Fixes #1688

<hr>

## Type of change 📝

- [x] Add a new project
- [] Modified or enhanced the existing projects
- [] Improve the readme of any project

<hr>

## Domain of Contribution 📊
- [] Project using only HTML & CSS
- [x] Project using HTML, CSS & JS
- [] Project using ReactJs

<hr>
 
## Checklist ✅

Please delete options that are not relevant. In order to tick the check box just put x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Recommended) 📸

https://user-images.githubusercontent.com/100334178/168476669-8e2e9b37-9125-4d5a-9788-ee03397489c7.mp4

### CODE REVIEW

**Comment by Mrjoy832** [comment]
image
Where is JS file?

**Comment by aaryahjolia** [comment]
https://replit.com/@codewithharry/Myntra-Clone#index.html

**Comment by i-am-aisha** [comment]
> image Where is JS file?

Js file is empty so i didn't include Js file in code i just mention it. The code for everything is in files which are present in the commit. Thankyou..

**Comment by Mrjoy832** [comment]
@i-am-aisha https://replit.com/@codewithharry/Myntra-Clone#index.html copied from here

**Comment by Mrjoy832** [comment]
## As You havenot replied it ...I am taking as it's under plag..So Sorry to say but I am Closing this

**Comment by i-am-aisha** [comment]
sorry i was unable to reply my laptop was in service center.
regarding this Pr.. yes i learn how to make myntra clone from this source but i make this clone own so please try to understand if its possible please reopen my Pr.

**Pull request merged**
