### PR TITLE
Temperature Convereter Website

### LINKED ISSUE #672: Temperature Converter Website
**Project title**
(Temperature Converter Website)

**Project Description**
(This is the Temperature Converter Website. In this Website, User will have to input a temperature that should be either in Fahrenheit or in Celsius and then press a "CONVERT" button. After that The converted temperature will then be displayed with the correct unit. ) 

**Stack**:

- [x] Html
- [x] CSS
- [x] JavaScript

### PR DESCRIPTION
**Pull request by priyanshu688**
<hr>

## Temperature Converter Website 📜

Fixes #672

<hr>

## Documentation 📝

- [x] Add a new project

<hr>

## Domain of Contribution 📊

- [x] Project using HTML, CSS & JS

<hr>
 
## Checklist ✅

- [x] I have performed a self-review of my own code or work..
- [x] My changes generates no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Optional) 📸

Add the screenshot of the changes you have made
Temperature Converter
[
Temperature Converter
](url)

### CODE REVIEW

**Comment by priyanshu688** [comment]
@khushi-purwar Kindly review & merge this

**Review by khushi-purwar — CHANGES_REQUESTED** [review]
Add readme file.

**Comment by priyanshu688** [comment]
@khushi-purwar Okh

**Comment by priyanshu688** [comment]
@khushi-purwar Done with changes. Kindly review & merge this.

**Comment by gurjeetsinghvirdee** [comment]
@priyanshu688 This branch is 2 commits ahead, 191 commits behind khushi-purwar/WebDev-ProjectKart:master.

**Comment by gurjeetsinghvirdee** [comment]
@priyanshu688 This branch is 3 commits ahead, 346 commits behind khushi-purwar/WebDev-ProjectKart:master.

**Pull request merged**
