### PR TITLE
Wikipedia

### LINKED ISSUE #1571: Wikipedia Search
**Project title**
Wikipedia Search

**Project Description**
Search Article On Wikipedia
**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript
- [] ReactJS

image

### PR DESCRIPTION
**Pull request by DragonUncaged**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. 

Fixes #1571 

<hr>

## Type of change 📝

Please delete options that are not relevant. In order to tick the check box just put x inside them for example [x] like this

- [x] Add a new project
- [] Modified or enhanced the existing projects
- [] Improve the readme of any project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant. In order to tick the check box just put x inside them for example [x] like this

- [x] Project using only HTML & CSS
- [] Project using HTML, CSS & JS
- [] Project using ReactJs

<hr>
 
## Checklist ✅

Please delete options that are not relevant. In order to tick the check box just put x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>

### CODE REVIEW

**Comment by DragonUncaged** [comment]
I can add the same project with changes. In this repos @gurjeetsinghvirdee

**Comment by DragonUncaged** [comment]
@gurjeetsinghvirdee  I have made changes in 
https://github.com/swapnilsparsh/30DaysOfJavaScript/pull/716

and Submitted both the project will be different.
I am sending pull request. to https://github.com/swapnilsparsh/30DaysOfJavaScript/pull/716

**Comment by gurjeetsinghvirdee** [comment]
> @gurjeetsinghvirdee  I have made changes in 
> https://github.com/swapnilsparsh/30DaysOfJavaScript/pull/716
> 
> and Submitted both the project will be different.
> I am sending pull request. to https://github.com/swapnilsparsh/30DaysOfJavaScript/pull/716

Then ok I did'nt check css

**Comment by DragonUncaged** [comment]
> > @gurjeetsinghvirdee  I have made changes in
> > [swapnilsparsh/30DaysOfJavaScript#716](https://github.com/swapnilsparsh/30DaysOfJavaScript/pull/716)
> > and Submitted both the project will be different.
> > I am sending pull request. to [swapnilsparsh/30DaysOfJavaScript#716](https://github.com/swapnilsparsh/30DaysOfJavaScript/pull/716)
> 
> Then ok I did'nt check css

i am doing now i thouht i will do it it before you read it but you are very fast

**Comment by DragonUncaged** [comment]
Done Changes
https://github.com/swapnilsparsh/30DaysOfJavaScript/pull/763

**Comment by gurjeetsinghvirdee** [comment]
This content copied from codepen https://codepen.io/arshdkhn1/pen/pymzWz
cc: @Mrjoy832 remove labels

**Pull request merged**
