### PR TITLE
Adding popup-video-trailer

### PR DESCRIPTION
**Pull request by kalashvasaniya**
Hey I made popup-video-trailerr Project Which Is Very Good!

This Project is very Helpfull,
I Make This Project With the help of HTML, CSS & JavaScript,

The CSS & JavaScript Code are Available in very well mannered! & Easy to understand!

### CODE REVIEW

**Comment by Mrjoy832** [comment]
# Not Accepting New PR's

**Comment by kalashvasaniya** [comment]
> # Not Accepting New PR's

But you will assign me 1 week ago?!!!

**Comment by Mrjoy832** [comment]
> > # Not Accepting New PR's
> 
> But you will assign me 1 week ago?!!!

## Attach issue link in PR description , so that can understand about which issue

**Comment by kalashvasaniya** [comment]
> > > # Not Accepting New PR's
> > 
> > 
> > But you will assign me 1 week ago?!!!
> 
> ## Attach issue link in PR description , so that can understand I about which issue

Done!

**Comment by kalashvasaniya** [comment]
> > > # Not Accepting New PR's
> > 
> > 
> > But you will assign me 1 week ago?!!!
> 
> ## Attach issue link in PR description , so that can understand I about which issue

Pls. Merge this PR!

**Comment by Mrjoy832** [comment]
> > > > # Not Accepting New PR's
> > > 
> > > 
> > > But you will assign me 1 week ago?!!!
> > 
> > 
> > ## Attach issue link in PR description , so that can understand I about which issue
> 
> Pls. Merge this PR!

I had my exam..wait I will verify

**Comment by kalashvasaniya** [comment]
> > > > > # Not Accepting New PR's
> > > > 
> > > > 
> > > > But you will assign me 1 week ago?!!!
> > > 
> > > 
> > > ## Attach issue link in PR description , so that can understand I about which issue
> > 
> > Pls. Merge this PR!
> 
> I had my exam..wait I will verify

Ok but pls. As soon as possible :)

**Comment by Mrjoy832** [comment]
You had made issue almost around 10th May , and the PR making was closed on 16th May
image
You had 6 days to make it ...but you make PR 5 days ago...So we cannot accept this

**Comment by kalashvasaniya** [comment]
> You had made issue almost around 10th May , and the PR making was closed on 16th May
> image
> You had 6 days to make it ...but you make PR 5 days ago...So we cannot accept this 

Pls. Accept this pls. , This is last one

**Pull request closed without merging**
