### PR TITLE
<Added the folder for movie website issue-91>

### LINKED ISSUE #91: Movie Website
**Project title**
Creating a movie website using HTML, CSS, and JavaScript.

**Project Description**
Hi @khushi-purwar, I would love to create a classic movie website using HTML, CSS, and JavaScript. Please assign me to this issue so that I can start working.I am really excited to work on this project
Thank You

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

### PR DESCRIPTION
**Pull request by mishramuskaan24**
<hr>

## Description 📜

Hi @khushi-purwar  and @meinhoonharsh . I have resolved the issue-91 and added the necessary files for movie website using HTML,CSS and Javascript. Please check the same and add the pull request.

Fixes #91

<hr>

## Type of change 📝

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Add a new project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Project using HTML, CSS & JS

<hr>
 
## Checklist ✅

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Optional) 📸

Add the screenshot of the changes you have made

### CODE REVIEW

**Comment by mishramuskaan24** [comment]
@khushi-purwar @meinhoonharsh please check it once and merge the pull request !!!

**Review by meinhoonharsh — CHANGES_REQUESTED** [review]
Would be Great, If you can add any Screenshots/GIF or live link

**Comment by mishramuskaan24** [comment]
> Would be Great, If you can add any Screenshots/GIF or live link

Ya sure !!!! @meinhoonharsh @khushi-purwar 
 Here is the live link :
https://moviedekhoo.netlify.app/
please review the same and update me further

**Review by meinhoonharsh — APPROVED** [review]
LGTM

**Comment by mishramuskaan24** [comment]
> LGTM

great !!!!

**Comment by mishramuskaan24** [comment]
Hiii .....
@meinhoonharsh @khushi-purwar
 Please merge my pull request if there are no further conflicts with base branch.

**Review by khushi-purwar — APPROVED** [review]

**Pull request merged**
