### PR TITLE
Added Fibonacci checker 

### PR DESCRIPTION
**Pull request by eswarbhageerath**
This is the PR for the issue Fibonacci checker #804

### CODE REVIEW

**Comment by gurjeetsinghvirdee** [comment]
attach ss or video what you make

**Comment by eswarbhageerath** [comment]
This is how my project works, When you open the project , you can see the following Page
ss1


In the input box, We have to enter any number and press submit button to know about given number


ss2

**Comment by eswarbhageerath** [comment]
@gurjeetsinghvirdee I have added the required screenshots..please review my PR

**Review by gurjeetsinghvirdee — APPROVED** [review]
LGTM

**Comment by eswarbhageerath** [comment]
Isn't this project eligible for level 3 sir?

**Review by gurjeetsinghvirdee — CHANGES_REQUESTED** [review]
Bro, you added ASCII Generator folder in this PR remove that files

**Comment by eswarbhageerath** [comment]
Sorry for inconvenience sir, I have deleted that...

**Comment by eswarbhageerath** [comment]
@gurjeetsinghvirdee ...Please review my PR sir

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Review by khushi-purwar — APPROVED** [review]

**Pull request merged**
