### PR TITLE
Added Password Strength Checker

### LINKED ISSUE #974: Adding Password Strength Calculator
**Project title**
Password Strength Calculator

**Project Description**
Password Strength Calculator which shows the strength of the password entered in terms of a percentage bar.

**Stack**:  

- [x] Html
- [x] CSS
- [x] JavaScript

### PR DESCRIPTION
**Pull request by LiQuiD-404**
<hr>

## Description 📜

A simple javascript project to check the user's password strength.

Fixes #974 

<hr>

## Type of change 📝

- [x] Add a new project

<hr>

## Domain of Contribution 📊

- [x] Project using HTML, CSS & JS

<hr>
 
## Checklist ✅

- [x] I have performed a self-review of my own code or work.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Recommended) 📸
snip1

### CODE REVIEW

**Comment by Mrjoy832** [comment]
New PR's will not be accepted..
image

**Comment by LiQuiD-404** [comment]
@Mrjoy832 It was a previous issue that's why I made this PR. Sorry

**Comment by Mrjoy832** [comment]
> @Mrjoy832 It was a previous issue that's why I made this PR. Sorry

make it same in any other project..like Dev-script or Ace-frontend or 30daysJS

**Comment by Mrjoy832** [comment]
> > @Mrjoy832 It was a previous issue that's why I made this PR. Sorry
> 
> make PR of it same in any other project..like Dev-script or Ace-frontend or 30daysJS

**Comment by LiQuiD-404** [comment]
@Mrjoy832 Alright. Thank you.

**Pull request closed without merging**
