### PR TITLE
adding BMI calculator

### LINKED ISSUE #687: BMI CALCULATOR
**Project title**

BMI CALCULATOR

**Project Description**

A web app to calculate BMI, based on entered values.

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

### PR DESCRIPTION
**Pull request by AnIkeT126**
<hr>

A web app to calculate BMI, based on entered values.

Please include a summary of the change and which issue is fixed. 

Fixes #687 

<hr>

## Type of change 📝

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Add a new project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Project using HTML, CSS & JS

<hr>
 
## Checklist ✅

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Optional) 📸

image

### CODE REVIEW

**Comment by AnIkeT126** [comment]
@khushi-purwar please merge this PR, upon reviewing it.

**Comment by AnIkeT126** [comment]
@khushi-purwar please merge this PR, upon reviewing it.

**Comment by AnIkeT126** [comment]
@khushi-purwar Can you please review this PR and merge it upon finding it correct.

**Comment by gurjeetsinghvirdee** [comment]
Already in our repo, make something different or I have to make a duplicate label

**Pull request closed without merging**
