### PR TITLE
Car game

### LINKED ISSUE #1351: Car Game
**Project title**
Car Game

**Project Description**
Avoid the Obstacles

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript
- [] ReactJS
previewOne

### PR DESCRIPTION
**Pull request by DragonUncaged**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. 

Fixes #1351 

<hr>

## Type of change 📝

Please delete options that are not relevant. In order to tick the check box just put x inside them for example [x] like this

- [] Add a new project
- [] Modified or enhanced the existing projects
- [] Improve the readme of any project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant. In order to tick the check box just put x inside them for example [x] like this

- [] Project using only HTML & CSS
- [x] Project using HTML, CSS & JS
- [] Project using ReactJs

<hr>
 
## Checklist ✅

Please delete options that are not relevant. In order to tick the check box just put x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Recommended) 📸
previewOne

### CODE REVIEW

**Comment by gurjeetsinghvirdee** [comment]
How can you make a PR before assigning? @DragonUncaged

**Comment by DragonUncaged** [comment]
> How can you make a PR before assigning? @DragonUncaged

Ohh !!! Okay next i will not raise PR before assigning

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Comment by DragonUncaged** [comment]
but you have not assigned I think.

**Comment by gurjeetsinghvirdee** [comment]
> but you have not assigned I think.

ignore it now, I'm already confused at a time after checking 30+ PR

will assign you In issue

**Pull request merged**
