### PR TITLE
Added Lorem Ipsum React App

### LINKED ISSUE #605: Lorem Ipsum Generator
**Project title**
Lorem Ipsum Generator

**Project Description**
Its kinda feel useless, but ask its value to a designer. Lorem Ipsum really help to fast forward your designing stages. Just put some random text for the reference and there you go.

**Stack**:  

- [x] ReactJS

**ScreenShots**

### PR DESCRIPTION
**Pull request by Abh1shekSingh**
<hr>

## Description 📜

Lorem Ipsum App is added, you can generate lorem ipsum text for your design end up saving alot of time while designing a app or web app design

Fixes #605 

<hr>

## Type of change 📝

- [x] Add a new project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Project using ReactJs

<hr>
 
## Checklist ✅

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 

> would be great if you can add a Screenshot/GIF or live preview link in the PR description

DONE !

### CODE REVIEW

**Review by meinhoonharsh — CHANGES_REQUESTED** [review]
would be great if you can add a Screenshot/GIF or live preview link in the PR description

**Comment by Abh1shekSingh** [comment]
@meinhoonharsh Done Brother

**Review by khushi-purwar — APPROVED** [review]

**Comment by gurjeetsinghvirdee** [comment]
Another one I got
[Lorem Ipsum](https://github.com/Sahu-Nihar/Lorem-Ipsum_React-Project)
[Live View](https://lorem-ipsum-react-project.netlify.app/)


bro @meinhoonharsh check code before giving approval

**Comment by Abh1shekSingh** [comment]
@gurjeetsinghvirdee @meinhoonharsh  again I would say the same thing as told before in Previous comment of other PR. That this is something that comes under cloning. Like Instagram clones. I am making these projects my self after learning the Techs.

**Comment by Abh1shekSingh** [comment]
@gurjeetsinghvirdee NO wtell me what is your problem here.

**Comment by Abh1shekSingh** [comment]
@gurjeetsinghvirdee Keep doing you dirty deeds. There is no point of winning by doing your dirty deeds. instead work hard like others .

**Pull request merged**
