### PR TITLE
Facebook UI Clone

### LINKED ISSUE #664: Facebook UI  Clone
**Project title**
Facebook UI  Clone 

**Project Description**
It's Facebook UI  Clone  using HTML,CSS,JS

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [X] Html
- [X] CSS
- [X] JavaScript

### PR DESCRIPTION
**Pull request by Mrjoy832**
<hr>

## Description 📜
Added Fcaebook Homepage Clone .

Fixes #664 

<hr>

## Type of change 📝

- [X] Add a new project

<hr>

## Domain of Contribution 📊

- [X] Project using only HTML & CSS

<hr>
 
## Checklist ✅

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Optional) 📸

https://user-images.githubusercontent.com/77873383/163515692-3a3eecdd-1085-464f-8e88-fa954ddc0646.mp4

### CODE REVIEW

**Comment by Mrjoy832** [comment]
@khushi-purwar please check

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Comment by gurjeetsinghvirdee** [comment]
@Mrjoy832 conflicts solve kre

**Comment by Mrjoy832** [comment]
> @Mrjoy832 conflicts solve kre

Okay 🙃🙃

**Comment by Mrjoy832** [comment]
@gurjeetsinghvirdee , created new PR, Closing this one https://github.com/khushi-purwar/WebDev-ProjectKart/pull/897

**Pull request closed without merging**
