### PR TITLE
Added Online Education Platform

### LINKED ISSUE #363: Add Online Education Platform
**Project title**
Digital Education Platform

**Project Description**
A platform which contains everything required to cover in online like the courses, teachers, materials, etc.
Please assign this to me. I'm a contributor at GSSoC'22.

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

### PR DESCRIPTION
**Pull request by bosedipayan**
<hr>

## Description 📜

Successfully Resolved issue https://github.com/khushi-purwar/WebDev-ProjectKart/issues/363 by adding online education site . I have also added working photos in the project folder and also provided hosted link here.
It is a website which contain details and blog on online education system.
LINK : https://online-education-611903.netlify.app/

Fixes #363

<hr>

## Type of change 📝

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x ] Add a new project
- [x ] Modified or enhanced the existing projects

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x ] Project using HTML, CSS & JS

## Checklist ✅
Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x ] I have performed a self-review of my own code or work.
- [x ] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Optional) 📸

<hr>
 

online-home
online-courses
online-teachers html
online-end

### CODE REVIEW

**Comment by bosedipayan** [comment]
Kindly review and merge the PR.

Thank You !

**Comment by khushi-purwar** [comment]
Add the readme file.

**Comment by bosedipayan** [comment]
[README.md](https://github.com/khushi-purwar/WebDev-ProjectKart/files/8481209/README.md)

**Comment by gurjeetsinghvirdee** [comment]
> [README.md](https://github.com/khushi-purwar/WebDev-ProjectKart/files/8481209/README.md)

Add a readme file to your project folder not here

**Review by gurjeetsinghvirdee — CHANGES_REQUESTED** [review]
Add a readme file to your project folder not here

**Comment by bosedipayan** [comment]
Then, I need to upload the project files once again. Could I do that ?

**Comment by bosedipayan** [comment]
Okay, then could I add it in review changes of files changed section.

**Review by bosedipayan — COMMENTED** [review]
> Okay, then could I add it in review changes of files changed section.

Do I need to add file here

**Comment by gurjeetsinghvirdee** [comment]
> > Okay, then could I add it in review changes of files changed section.
> 
> Do I need to add file here

In your project folder

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Comment by gurjeetsinghvirdee** [comment]
@bosedipayan This PR will merge on 19 bcoz right now we are checking old merged PRs

**Pull request merged**
