### PR TITLE
Added E-commerce website

### LINKED ISSUE #1190: E-Commerce website with functionalities
**Project title**
E-commerce website

**Project Description**
This website will have functionalities like login signup from local storage session (can make it with php also) and also it will have option to add to cart (to local storage) and also the links will be linked to original products.

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript
- [] ReactJS

### PR DESCRIPTION
**Pull request by aaryahjolia**
<hr>

## Description 📜

Included E-commerce website with many functionalities (You can find it out in readme.md).

Functionalities :

1. Login / sign up using local storage
2. Dark / Light theme
3. Product images linked to original product
4. Cart functionalities (products can be added to cart and it will be there till you remove them)
5. Fully Responsive

Fixes #1190 

<hr>

## Type of change 📝

- [x] Add a new project

<hr>

## Domain of Contribution 📊

- [x] Project using HTML, CSS & JS

<hr>
 
## Checklist ✅

- [x] I have performed a self-review of my own code or work.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Recommended) 📸

image

image

More images in readme.md file

### CODE REVIEW

**Comment by aaryahjolia** [comment]
@gurjeetsinghvirdee Please Review my PR.

**Comment by gurjeetsinghvirdee** [comment]
@aaryahjolia attach video

**Comment by aaryahjolia** [comment]
> @aaryahjolia attach video


https://user-images.githubusercontent.com/82600388/167143885-419aed9a-eac2-49da-8fd7-33b4719b2214.mp4

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Comment by gurjeetsinghvirdee** [comment]
@aaryahjolia Mera mnn level10 dene ka h par aisa koi label ni h✨
Great work

**Pull request merged**
