### PR TITLE
Guess the word game

### PR DESCRIPTION
**Pull request by codersmiti**
<hr>

## Description 📜

I have created guess the word game using html,css and javascript

Fixes: #406

<hr>

## Type of change 📝

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Add a new project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Project using HTML, CSS & JS

<hr>
 
## Checklist ✅

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Optional) 📸

Add the screenshot of the changes you have made
guess the word game

### CODE REVIEW

**Comment by codersmiti** [comment]
please review this @khushi-purwar

**Comment by khushi-purwar** [comment]
Files are not pushed properly. Kindly check at your end.

**Comment by codersmiti** [comment]
now can you check it?@khushi-purwar

**Review by meinhoonharsh — CHANGES_REQUESTED** [review]
Things are perfect to get merged
The only thing is, you have shifted the code inside `gssoc/guess.... Javascript` instead of directly into `Guess .... JavaScript`

**Comment by codersmiti** [comment]
I have made the changes @meinhoonharsh .Please review it

**Review by meinhoonharsh — CHANGES_REQUESTED** [review]
That zip is not making any sense here to get merged 🙃

**Pull request closed without merging**
