### PR TITLE
This is my first commit with all the required files along with readme

### LINKED ISSUE #41: Newsletter Signup Page
**Project title**
Newsletter Signup

**Project Description**
I want  to add a newsletter signup page which has api call with a newsletter.
@khushi-purwar If you find this to be required Please assign me this issue, I am a GSSOC'22 contributor.

**Stack**:  
- [x] Html
- [x] CSS
- [x] JavaScript
- [x] Node.js

### PR DESCRIPTION
**Pull request by uhini0201**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. 

Fixes #41 

<hr>

## Type of change 📝

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Add a new project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Project using only HTML & CSS
- [x] Project using HTML, CSS & JS

<hr>
 
## Checklist ✅

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Optional) 📸

Add the screenshot of the changes you have made
output1
output2
output3

### CODE REVIEW

**Comment by uhini0201** [comment]
@nirbhay12345 @amyra98 please review this and let me know if any other changes are required.

**Review by meinhoonharsh — CHANGES_REQUESTED** [review]
Seems you've done great work from the Screenshots mentioned in the PR, but don't know I can't see any file in the `Files Changed` Section. Looks like you forgot to commit/add or any other issue

**Comment by uhini0201** [comment]
let me see

**Comment by uhini0201** [comment]
@meinhoonharsh can you please check now??

**Pull request closed without merging**
