### PR TITLE
adding covid cases tracker

### LINKED ISSUE #1018: Covid Cases Tracker
**Project title**

Covid Cases Tracker

**Project Description**

A web-app-based Covid Cases Tracker, that  shows total number of confirmed cases, active cases and death in India of a particular day, After fetching the details from API.

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

### PR DESCRIPTION
**Pull request by AnIkeT126**
<hr>

## Description 📜

A web-app-based Covid Cases Tracker, that shows total number of confirmed cases, active cases and death in India of a particular day, After fetching the details from API.

Fixes #1018 

<hr>

## Type of change 📝

Please delete options that are not relevant. And in order to tick the check box just put x inside them for example [x] like this

- [x] Add a new project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant. And in order to tick the check box just put x inside them for example [x] like this

- [x] Project using HTML, CSS & JS

<hr>
 
## Checklist ✅

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Recommended) 📸

https://user-images.githubusercontent.com/82095877/165590110-f591e16b-4954-4503-82a7-d7f76543674a.mp4

image

### CODE REVIEW

**Comment by AnIkeT126** [comment]
@gurjeetsinghvirdee please review this PR, and merge this upon finding it correct.

**Comment by gurjeetsinghvirdee** [comment]
your files change into binary sub module better to make a new PR @AnIkeT126

**Comment by AnIkeT126** [comment]
> your files change into binary sub module better to make a new PR @AnIkeT126

ok
but is it not possible for you check like this, bcoz i tried twice and idk why this is making it as a module.

**Comment by AnIkeT126** [comment]
> > your files change into binary sub module better to make a new PR @AnIkeT126
> 
> ok but is it not possible for you check like this, bcoz i tried twice and idk why this is making it as a module.

if possible please review this, I have even provided a video in pr for your easy reference,

**Comment by gurjeetsinghvirdee** [comment]
> > your files change into binary sub module better to make a new PR @AnIkeT126
> 
> ok but is it not possible for you check like this, bcoz i tried twice and idk why this is making it as a module.

I can't review bcoz Github don't have access to binary sub folders, these folders can't even open

**Comment by gurjeetsinghvirdee** [comment]
Screenshot (921)


look there is no option to open this folder @AnIkeT126

**Comment by AnIkeT126** [comment]
> > > your files change into binary sub module better to make a new PR @AnIkeT126
> > 
> > 
> > ok but is it not possible for you check like this, bcoz i tried twice and idk why this is making it as a module.
> 
> I can't review bcoz Github don't have access to binary sub folders, these folders can't even open

sure

**Pull request closed without merging**
