### PR TITLE
Markdown Blog

### LINKED ISSUE #1252: Markdown Blog
**Project title**
Markdown Blogs

**Project Description**
Markdown blogs with Next JS 

**Stack**:  
And in order to tick the check box just put x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Next JS

### PR DESCRIPTION
**Pull request by gurjeetsinghvirdee**
<hr>

## Description 📜

This is a Markdown-powered Next.js blog!

Fixes #1252 

<hr>

## Type of change 📝

Please delete options that are not relevant. In order to tick the check box just put x inside them for example [x] like this

- [x] Add a new project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant. In order to tick the check box just put x inside them for example [x] like this

- [x] Project using Next Js

<hr>
 
## Checklist ✅

Please delete options that are not relevant. In order to tick the check box just put x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] My changes generate no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Recommended) 📸

https://user-images.githubusercontent.com/73753957/167090084-9b0b2f06-84c8-4cdb-bdd6-cbbf0715c65d.mp4

### CODE REVIEW

**Comment by yash-25log** [comment]
@gurjeetsinghvirdee bhai yr mujhe bhi btado konsa recorder use krte
mere pc me record nhi ho rha ptani kyo
laptop me to jisse me krta ho rha
pr abhi laptop khrb hai

**Comment by gurjeetsinghvirdee** [comment]
> @gurjeetsinghvirdee bhai yr mujhe bhi btado konsa recorder use krte
> mere pc me record nhi ho rha ptani kyo
> laptop me to jisse me krta ho rha
> pr abhi laptop khrb hai

https://www.freescreenrecording.com/

**Comment by gurjeetsinghvirdee** [comment]
Wmv format me record hoti h online convert krlena 
Wmv to mp4

**Comment by yash-25log** [comment]
> Wmv format me record hoti h online convert krlena Wmv to mp4

thanks dude

**Review by khushi-purwar — APPROVED** [review]

**Pull request merged**
