### PR TITLE
alumni tracking system

### LINKED ISSUE #989: Alumni Tracking System
**Project Description**
a system that brings college graduate together and connected

dynamic with various features

this template was originally created for mits gwallior hackathon

now i would like to contribute it to open source

implies backend + user friendly UI and dashboard

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [] Html
- [] CSS
- [] JavaScript
- [x] ReactJS
- [x] NodeJS

### PR DESCRIPTION
**Pull request by yash-25log**
<hr>

## Description 📜
a system that brings college graduate together and connected

dynamic with various features

this template was originally created for mits gwallior hackathon

now i would like to contribute it to open source

implies backend + user friendly UI and dashboard

Fixes #989 

<hr>

## Type of change 📝

Please delete options that are not relevant. And in order to tick the check box just put x inside them for example [x] like this

- [x] Add a new project
- [] Modified or enhanced the existing projects
- [] Improve the readme of any project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant. And in order to tick the check box just put x inside them for example [x] like this

- [] Project using only HTML & CSS
- [] Project using HTML, CSS & JS
- [] Project using ReactJs

<hr>
 
## Checklist ✅

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [] I have performed a self-review of my own code or work.
- [] I have commented on my code, particularly in hard-to-understand areas.
- [] My changes generates no new warnings.
- [] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Recommended) 📸
https://mitss.vercel.app/

backend haven't be hosted along with dashboard yet

image

### CODE REVIEW

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Comment by yash-25log** [comment]
@gurjeetsinghvirdee bhai backend project tha

**Comment by yash-25log** [comment]
still level 2

**Comment by yash-25log** [comment]
waise abhi soye nhi lol

**Comment by gurjeetsinghvirdee** [comment]
> waise abhi soye nhi lol

Sona ye ky hota h

**Pull request merged**
