### PR TITLE
Number guessing game.

### PR DESCRIPTION
**Pull request by TechnicalAmanjeet**
done with this project.
1.) created simple ui .
2.) given functionality through JavaScript that user can play this game. 
3.) updated the readme.md file as well.

### CODE REVIEW

**Comment by khushi-purwar** [comment]
Kindly correct the spelling of Guessing/Guess in the code and you have not follow the project structure. Arrange all your files according to the project structure (given in the readme of the repo).

**Comment by khushi-purwar** [comment]
Great work @TechnicalAmanjeet

**Comment by TechnicalAmanjeet** [comment]
Thank you. what should I do next?? could you please suggest something. like if you know some other repo for web dev where I can contribute then let me know?.

**Comment by khushi-purwar** [comment]
Yes, I know one repository where you can contribute. You can join this https://discord.gg/gtYUZQSjTt. 
Here you will get many projects related to web development.

**Comment by TechnicalAmanjeet** [comment]
could you please share 5hat repo link?

**Comment by khushi-purwar** [comment]
> could you please share 5hat repo link?

https://github.com/arpit456jain/Amazing-Css-Effects

**Pull request merged**
