### PR TITLE
 case converter added

### LINKED ISSUE #236: Case-Converter
**Project name**
Case Converter.
Case Converter that converts your  string into the desired case.

### PR DESCRIPTION
**Pull request by Aniket1026**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. 

Fixes #236

<hr>

## Type of change 📝

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [ ] Add a new project
- [ ] Modified or enhanced the existing projects
- [ ] Improve the readme of any project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [ ] Project using only HTML & CSS
- [ ] Project using HTML, CSS & JS
- [ ] Project using ReactJs

<hr>
 
## Checklist ✅

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [ ] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generates no new warnings.
- [ ] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Optional) 📸

Add the screenshot of the changes you have made

### CODE REVIEW

**Comment by khushi-purwar** [comment]
> ## Description 📜
> Please include a summary of the change and which issue is fixed.
> 
> Fixes #<issue_number_here>
> 
> ## Type of change 📝
> Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this
> 
> * [ ]  Add a new project
> * [ ]  Modified or enhanced the existing projects
> * [ ]  Improve the readme of any project
> 
> ## Domain of Contribution 📊
> Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this
> 
> * [ ]  Project using only HTML & CSS
> * [ ]  Project using HTML, CSS & JS
> * [ ]  Project using ReactJs
> 
> ## Checklist ✅
> Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this
> 
> * [ ]  I have performed a self-review of my own code or work.
> * [ ]  I have commented my code, particularly in hard-to-understand areas.
> * [ ]  My changes generates no new warnings.
> * [ ]  I'm GSSoC'22 contributor
> 
> ## Screenshots / Gif (Optional) 📸
> Add the screenshot of the changes you have made

Please fill the detail of PR template like issue number, project description and so on

**Comment by khushi-purwar** [comment]
Resolve the conflicts as well.

**Comment by Aniket1026** [comment]
ok the conflict has been resolved . plzzz do merge

**Comment by Aniket1026** [comment]
well this is my first contribution . I'm not aware of things but if there are no conflicts do merge plzzzzzzzzzzz.

**Comment by khushi-purwar** [comment]
Please mention the issue number.

**Comment by Aniket1026** [comment]
issue number is 236

**Comment by Aniket1026** [comment]
is there still anything I'm doing wrong in order to get my PR merged ?

**Review by khushi-purwar — CHANGES_REQUESTED** [review]
Add the readme file also.

**Comment by Aniket1026** [comment]
I added the readme file. If all goes right plzz merge my first PR

**Review by khushi-purwar — APPROVED** [review]

**Pull request merged**
