### PR TITLE
Pomodoro Clock added

### LINKED ISSUE #462: Pomodoro Clock
**Project title**
Pomodoro Clock

**Project Description**
Pomodoro Clock for pomodoro sessions.

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript
- [ ] ReactJS

### PR DESCRIPTION
**Pull request by rajprem4214**
<hr>

## Description 📜

A clock for your pomodoro sessions.

Fixes #462 

<hr>

## Type of change 📝

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Add a new project
- [ ] Modified or enhanced the existing projects
- [ ] Improve the readme of any project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [ ] Project using only HTML & CSS
- [x] Project using HTML, CSS & JS
- [ ] Project using ReactJs

<hr>
 
## Checklist ✅

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Optional) 📸

pomo

### CODE REVIEW

**Review by meinhoonharsh — CHANGES_REQUESTED** [review]
Just add a Screenshot/GIF or preview link and it's GTG

**Comment by khushi-purwar** [comment]
Also resolve the conflict

**Comment by rajprem4214** [comment]
> Just add a Screenshot/GIF or preview link and it's GTG

DOne

**Comment by rajprem4214** [comment]
> Also resolve the conflict

Done

**Review by khushi-purwar — APPROVED** [review]

**Pull request merged**
