### PR TITLE
Flash Cards

### LINKED ISSUE #1081: Flash Cards
**Project title**

Flash Cards 

**Project Description**

Flash Cards based game, for you remember your subjects in more detail.

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

### PR DESCRIPTION
**Pull request by AnIkeT126**
<hr>

## Description 📜

Flash Cards based game, for you remember your subjects in more detail.

Fixes #1081 

<hr>

## Type of change 📝

Please delete options that are not relevant. And in order to tick the check box just put x inside them for example [x] like this

- [x] Add a new project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant. And in order to tick the check box just put x inside them for example [x] like this

- [x] Project using HTML, CSS & JS

<hr>
 
## Checklist ✅

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Recommended) 📸

https://user-images.githubusercontent.com/82095877/166245521-11970516-275e-481c-b4fa-d9cb6d48cb1b.mp4

### CODE REVIEW

**Comment by AnIkeT126** [comment]
@gurjeetsinghvirdee please review this PR.

**Comment by gurjeetsinghvirdee** [comment]
> @gurjeetsinghvirdee please review this PR.

Readme issue vps pdhle ek baar

**Comment by AnIkeT126** [comment]
> > @gurjeetsinghvirdee please review this PR.
> 
> Readme issue vps pdhle ek baar

kya matlab

**Comment by gurjeetsinghvirdee** [comment]
#1102

**Comment by AnIkeT126** [comment]
> #1102

Ok... I won't make any pr until tomorrow now, jab Tera man kre review kr dena

**Comment by AnIkeT126** [comment]
> > #1102
> 
> Ok... I won't make any pr until tomorrow now, jab Tera man kre review kr dena inko

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Pull request merged**
