### PR TITLE
Random_number_between_two_numbers

### LINKED ISSUE #1539: Random number between two numbers
**Project title**
Random number generator.

**Project Description**
### The idea behind this project
This is the prediction of how much you are lucky to get the expected output.

### How does it work
while loading the webpage you will have the two input files you just need to fill respectively and you will get the output as a random number.

**Stack**:  

And in order to tick the check box just put x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

for more details please refer to the attached images.

https://user-images.githubusercontent.com/73521123/167455008-4428d17c-1478-4d15-ad14-4a47f49565cd.mp4

Screenshot (187)

### PR DESCRIPTION
**Pull request by Kumar-Ankit56**
<hr>

## Description 📜

**Project title**
Random number generator.

**Project Description**
### The idea behind this project
This is the prediction of how much you are lucky to get the expected output.

### How does it work
while loading the webpage you will have the two input files you just need to fill respectively and you will get the output as a random number.

Fixes #1539  

<hr>

## Type of change 📝

Please delete options that are not relevant. And in order to tick the check box just put x inside them for example [x] like this

- [x] Add a new project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant. And in order to tick the check box just put x inside them for example [x] like this

- [x] Project using HTML, CSS & JS

<hr>
 
## Checklist ✅

Please delete options that are not relevant. And in order to tick the check box just put x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
## Screenshots / Gif (Recommended) 📸

https://user-images.githubusercontent.com/73521123/167266539-3774d2bf-9616-4182-a3a7-67c7769581ea.mp4](https://user-images.githubusercontent.com/73521123/167455008-4428d17c-1478-4d15-ad14-4a47f49565cd.mp4

Screenshot (187)

)

### CODE REVIEW

**Comment by Kumar-Ankit56** [comment]
@gurjeetsinghvirdee plz check it

**Comment by gurjeetsinghvirdee** [comment]
> @gurjeetsinghvirdee plz check it

not a mentor anymore

**Comment by Kumar-Ankit56** [comment]
> > @gurjeetsinghvirdee plz check it
> 
> not a mentor anymore

oh sorry can I know who is?

**Comment by gurjeetsinghvirdee** [comment]
> > > @gurjeetsinghvirdee plz check it
> > 
> > 
> > not a mentor anymore
> 
> oh sorry, can I know who is?

maybe nobody here😅

**Comment by Kumar-Ankit56** [comment]
> > > > @gurjeetsinghvirdee plz check it
> > > 
> > > 
> > > not a mentor anymore
> > 
> > 
> > oh sorry, can I know who is?
> 
> maybe nobody here😅

Oh, that's a deadly one 😅

**Comment by Kumar-Ankit56** [comment]
@Mrjoy832 plz review i.

**Review by Mrjoy832 — APPROVED** [review]

**Pull request merged**
