### PR TITLE
Added TicTacToe

### LINKED ISSUE #532: Tictactoe with computer
**Project title**
Tictactoe with computer

**Project Description**
Player will be playing tictactoe with computer

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript
- [] ReactJS

### PR DESCRIPTION
**Pull request by Atif0604**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. 

Fixes #532 

<hr>

## Type of change 📝

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Add a new project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Project using HTML, CSS & JS

<hr>
 
## Checklist ✅

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Optional) 📸

Add the screenshot of the changes you have made

tictactoe-dark

### CODE REVIEW

**Comment by Atif0604** [comment]
@khushi-purwar Please Review

**Review by gurjeetsinghvirdee — APPROVED** [review]
Looks good

**Comment by Atif0604** [comment]
Hey @gurjeetsinghvirdee in the issue section it has been assigned leve3 but here its level2 
any reasons?

**Comment by gurjeetsinghvirdee** [comment]
> Hey @gurjeetsinghvirdee in the issue section it has been assigned leve3 but here its level2 
> any reasons?

Ah same question again and again
Ignore that level3 label in ISSUES

Your PR difficulty level decides which label we put here

**Pull request merged**
