### PR TITLE
LUDO DICE

### LINKED ISSUE #728: LUDO DICE
**Project title**

LUDO DICE

**Project Description**

A web app based LUDO DICE

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

### PR DESCRIPTION
**Pull request by AnIkeT126**
<hr>

A web-app-based Roller for dice of Ludo.

Please include a summary of the change and which issue is fixed. 

Fixes #728 

<hr>

## Type of change 📝

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Add a new project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Project using HTML, CSS & JS

<hr>
 
## Checklist ✅

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Optional) 📸

image

### CODE REVIEW

**Comment by AnIkeT126** [comment]
@khushi-purwar please merge this PR, upon reviewing it.

**Comment by AnIkeT126** [comment]
@khushi-purwar please merge this PR, upon reviewing it.

**Comment by AnIkeT126** [comment]
@khushi-purwar Can you please review this PR and merge it upon finding it correct.

**Review by gurjeetsinghvirdee — APPROVED** [review]
LGTM

**Comment by AnIkeT126** [comment]
@gurjeetsinghvirdee are you are a moderator of this project ??

**Comment by AnIkeT126** [comment]
@khushi-purwar @gurjeetsinghvirdee when I was assigned this issue i was given a level label 3 as my other issues and PR, it seems that you have removed those to ass new, please understand that we worked on these issues considering the amount of points we were getting, so please restore my old level lables in all the PRs because I started working on them post the level label was addressed

**Review by khushi-purwar — APPROVED** [review]

**Pull request merged**
