### PR TITLE
Animated bear login form

### LINKED ISSUE #1668: Animated cute bear form  by javascript
**Project title**
Animated cute bear form  by javascript 

**Project Description**
Whenever you will type on any column, bear's eye will follow your blinking text-cursor. Bear will close it's eye when you will click on password column to fill.

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

### PR DESCRIPTION
**Pull request by mayank-del**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. 

Fixes #1668 

<hr>

## Type of change 📝

Please delete options that are not relevant. In order to tick the check box just put x inside them for example [x] like this

- [x] Add a new project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant. In order to tick the check box just put x inside them for example [x] like this

- [x] Project using HTML, CSS & JS

<hr>
 
## Checklist ✅

Please delete options that are not relevant. In order to tick the check box just put x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] My changes generate no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Recommended) 📸

Cute-Bear

### CODE REVIEW

**Comment by mayank-del** [comment]
@Gurdeep475 , @Mrjoy832 , please check and merge, else seven day will be over and bot will close the issue.

**Comment by Mrjoy832** [comment]
> @Mrjoy832 sir, you can merge this project in your repo

share whole window -screen of your laptop and make a demo video , put into readme

**Comment by Mrjoy832** [comment]
again to-do is disturbed , fix

**Comment by mayank-del** [comment]
@Mrjoy832 , I resolved every issues please merge it now.

**Comment by mayank-del** [comment]
@Mrjoy832  issues fixed and full screen gif also uploaded, now  you can merge it.

**Comment by Mrjoy832** [comment]
> @Mrjoy832 issues fixed and full screen gif also uploaded, now you can merge it.

vai tera har PR me TO-do me problem aa raha hain ...keep it same as main branch

**Comment by mayank-del** [comment]
Bhai

> > @Mrjoy832 issues fixed and full screen gif also uploaded, now you can merge it.
> 
> vai tera har PR me TO-do me problem aa raha hain ...keep it same as main branch

Bhai bss last curly brace ek line niche chala jaa raha hai, isse main project me koi problem nhi hoga , maine  apke repo se exact paste maara tha

**Comment by Mrjoy832** [comment]
> Bhai
> 
> > > @Mrjoy832 issues fixed and full screen gif also uploaded, now you can merge it.
> > 
> > 
> > vai tera har PR me TO-do me problem aa raha hain ...keep it same as main branch
> 
> Bhai bss last curly brace ek line niche chala jaa raha hai, isse main project me koi problem nhi hoga , maine apke repo se exact paste maara tha

okay fir korta hu merge thori der me 🤗

**Pull request merged**
