### PR TITLE
adding github profile

### PR DESCRIPTION
**Pull request by kalashvasaniya**
Hey I made github profile Project Which Is Very Good!

This Project is very Helpfull,
I Make This Project With the help of HTML, CSS & JavaScript,

The CSS & JavaScript Code are Available in very well mannered! & Easy to understand!

### CODE REVIEW

**Comment by gurjeetsinghvirdee** [comment]
Please check before making projects it's already there

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Comment by gurjeetsinghvirdee** [comment]
attach a video @kalashvasaniya

**Comment by kalashvasaniya** [comment]
> attach a video @kalashvasaniya

https://user-images.githubusercontent.com/88212870/165971565-3850924a-ae82-4d9f-b08e-52b00d90cc6b.mov

**Comment by gurjeetsinghvirdee** [comment]
Copied from here 

https://github.com/bradtraversy/50projects50days/tree/master/github-profiles

**Pull request closed without merging**
