### PR TITLE
React App (API)

### LINKED ISSUE #450: Fetch API using react app
**Project title**
Fetch API using react app

**Project Description**
That we add the get user button to API calls to get user data and have a loader while API fetches the data .

**Stack**:  
And in order to tick the check box just put x inside them for example - [x] like this. Please delete options that are not relevant.

- [] Html
- [] CSS
- [] JavaScript
- [] ReactJS

127682487-0fe5c6c4-dbea-46d9-b4cc-d05cf2dfcc8d
127682536-3775484a-e20e-41f0-978d-dd0ff130f933

### PR DESCRIPTION
**Pull request by iamrahulmahato**
<hr>

## Description 📜

That we add the get user button to API calls to get user data and have a loader while API fetches the data .

Fixes #450

<hr>

## Type of change 📝

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Add a new project
- [x] Modified or enhanced the existing projects
- [x] Improve the readme of any project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Project using HTML, CSS & JS
- [x] Project using ReactJs

<hr>
 
## Checklist ✅

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Optional) 📸
127682487-0fe5c6c4-dbea-46d9-b4cc-d05cf2dfcc8d
127682536-3775484a-e20e-41f0-978d-dd0ff130f933

### CODE REVIEW

**Comment by gurjeetsinghvirdee** [comment]
Are you make this your own? @iamrahulmahato

**Comment by iamrahulmahato** [comment]
@gurjeetsinghvirdee fully not I have also taken the help of a friend who previously has the experience with react

**Comment by gurjeetsinghvirdee** [comment]
Can you attach a video how it works @iamrahulmahato

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Comment by iamrahulmahato** [comment]
@gurjeetsinghvirdee Demo

https://user-images.githubusercontent.com/49890655/163271997-6bc4867b-6366-435a-9044-59404981f4ec.mp4

**Review by khushi-purwar — APPROVED** [review]

**Pull request merged**
