### PR TITLE
Adding Lights Out Game, Resolving issue #280

### LINKED ISSUE #280: Lights out Game
**Project title**

Lights Out Game

**Project Description**

This is a complex game designed on 5 * 5, 6 * 6 & 7 * 7 boards.
The basic idea behind the game is that initially some squares will be of color X and others will be of color Y, where X denotes light on and Y denotes light off.
You have to turn the light of all squares off or make them of color Y so as to say by flipping the tile, but the catch is that once you flip the tile to change its colo/light mod, not only its color change but the color of its adjacent neighbors in the X & Y direction also changes, so the complexity increases as you keep flipping the tile, neighbors also get changed. 
In the end, player wins if all tiles are turned off, i.e. all neighbors of all tiles are turned off. 

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript
- [x] ReactJS

### PR DESCRIPTION
**Pull request by AnIkeT126**
<hr>

## Description 📜

This is a complex game designed on 5 * 5, 6 * 6 & 7 * 7 boards.
The basic idea behind the game is that initially some squares will be of color X and others will be of color Y, where X denotes light on and Y denotes light off.
You have to turn the light of all squares off or make them of color Y so as to say by flipping the tile, but the catch is that once you flip the tile to change its colo/light mod, not only its color change but the color of its adjacent neighbors in the X & Y direction also changes, so the complexity increases as you keep flipping the tile, neighbors also get changed.
In the end, player wins if all tiles are turned off, i.e. all neighbors of all tiles are turned off.

Please include a summary of the change and which issue is fixed. 

Fixes #280 

<hr>

## Type of change 📝

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Add a new project
- [ ] Modified or enhanced the existing projects
- [ ] Improve the readme of any project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Project using only HTML & CSS
- [x] Project using HTML, CSS & JS
- [x] Project using ReactJs

<hr>
 
## Checklist ✅

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Optional) 📸

Add the screenshot of the changes you have made

Overview

### CODE REVIEW

**Comment by AnIkeT126** [comment]
@khushi-purwar can you please check this, I have done the game and it seems to be working fine, I have also added a woring video of the game in the public folder of the repository.

**Comment by AnIkeT126** [comment]
@khushi-purwar also, once you check this, please add a label to the PR for evaluation.

**Comment by AnIkeT126** [comment]
@khushi-purwar can you please check this once

**Comment by khushi-purwar** [comment]
You cannot add the django project in this repo. This repo is only for HTML, CSS , JS AND REACTJS. I am closing this PR as it is not valid.

**Pull request closed without merging**
