### PR TITLE
Added Memory Card Game

### LINKED ISSUE #669: Adding a Memory Card Game
**Project title**
Memory Card Game

**Project Description**
A simple Memory Card Game in which the player has two find two cards containing the same image.

**Stack**:  

- [x] Html
- [x] CSS
- [x] JavaScript

### PR DESCRIPTION
**Pull request by LiQuiD-404**
<hr>

## Description 📜

A simple web-based Memory Card game in which you have to match the images to win.

Fixes #669 

<hr>

## Type of change 📝

- [x] Add a new project

<hr>

## Domain of Contribution 📊

- [x] Project using HTML, CSS & JS

<hr>
 
## Checklist ✅

- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Optional) 📸

snip1

### CODE REVIEW

**Comment by gurjeetsinghvirdee** [comment]
add tech stacks screenshot in readme @LiQuiD-404

**Comment by LiQuiD-404** [comment]
@gurjeetsinghvirdee  I have already mentioned the tool I used in the "Built with" section of the Readme file. Kindly review.

**Review by gurjeetsinghvirdee — APPROVED** [review]
LGTM

**Comment by LiQuiD-404** [comment]
@gurjeetsinghvirdee  This is not a Level2 Issue. It was assigned to me as Level3. Kindly check

**Comment by gurjeetsinghvirdee** [comment]
> @gurjeetsinghvirdee  This is not a Level2 Issue. It was assigned to me as Level3. Kindly check

I will post this publically ask for if it is level2 issue or level3

**Comment by gurjeetsinghvirdee** [comment]
> @gurjeetsinghvirdee  This is not a Level2 Issue. It was assigned to me as Level3. Kindly check

Bro I'm a mentor or you
I know why people came here because no judge the code and put label3

But ab se aisa ni hoga

**Pull request merged**
