### PR TITLE
Admin Panel

### LINKED ISSUE #1577: Admin Panel
**Project title**
Admin Panel

**Project Description**
Admin dashboard where they check all things

**Stack**:  
And in order to tick the check box just put x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript
- [x] Bootstrap

### PR DESCRIPTION
**Pull request by gurjeetsinghvirdee**
<hr>

## Description 📜

Admin dashboard where they check all things

Fixes #1577 

<hr>

## Type of change 📝

Please delete options that are not relevant. In order to tick the check box just put x inside them for example [x] like this

- [x] Add a new project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant. In order to tick the check box just put x inside them for example [x] like this

- [x] Project using HTML, CSS, Bootstrap & JS

<hr>
 
## Checklist ✅

Please delete options that are not relevant. In order to tick the check box just put x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] My changes generate no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Recommended) 📸

https://user-images.githubusercontent.com/73753957/167558516-d9fe2da1-720c-47da-94ad-1d76456b11a0.mp4

### CODE REVIEW

**Comment by gurjeetsinghvirdee** [comment]
Responsive bhi hai me record krna bhul gya @Mrjoy832

**Comment by arpit456jain** [comment]
@khushi-purwar https://startbootstrap.com/previews/sb-admin-2

**Comment by Suvraneel** [comment]
@Mrjoy832  Are you a mentor to this project?

**Comment by Mrjoy832** [comment]
> @Mrjoy832 Are you a mentor to this project?

Yes I am mentor here ...I have also DM you discord kindly check...Suddenly over a Night I am Out from leaderboard...Dont ever know the reason..Kindly elaborate what happened?

**Comment by Mrjoy832** [comment]
> @khushi-purwar https://startbootstrap.com/previews/sb-admin-2
We have not lots of active mentor as You, I am also Mentor of LearnCPP and here(assigned 2 days before)...So it's not possible always to check always for every project is that plagarized or that? THough You think I am wrong send some of  mentors here ..I will be going out from here🙂 no issue... but @Suvraneel I am not getting any reason why by over a night from the Top of leaderboard I am just vanish?

**Pull request merged**
