### PR TITLE
Final Commit

### LINKED ISSUE #318: Add Feature of unit converter
**Project title**
Unit Converter

**Project Description**
All in one unit converter

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

### PR DESCRIPTION
**Pull request by kirteshmaskey**
<hr>

## Description 📜

Added new feature: unit converter.
Using this one can convert length, area, temperature, volume, mass, speed, time, data.

Fixes #318

<hr>

## Type of change 📝

- [x] Add a new project

<hr>

## Domain of Contribution 📊

- [x] Project using HTML, CSS & JS

<hr>
 
## Checklist ✅

- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>

### CODE REVIEW

**Review by meinhoonharsh — APPROVED** [review]
GTG @khushi-purwar You can merge this one

**Review by khushi-purwar — CHANGES_REQUESTED** [review]
Please mention the issue number

**Review by kirteshmaskey — COMMENTED** [review]
Done

**Comment by khushi-purwar** [comment]
> Done

Kindly mention the issue number so that PR gets merged successfully.

**Comment by kirteshmaskey** [comment]
> Kindly mention the issue number so that PR gets merged successfully.
Issue Number: 257

**Comment by khushi-purwar** [comment]
Have you created the issue for the same or you have created the PR directly?

**Comment by khushi-purwar** [comment]
> > Have you created the issue for the same or you have created the PR directly?
> 
> I have directly generated Pull Request.

No, this is wrong. First you have to create the issue , then issue will be assigned. Then you have to work on it. Then create the PR, then your PR will merged.

**Comment by kirteshmaskey** [comment]
> > > Have you created the issue for the same or you have created the PR directly?
> > 
> > 
> > I have directly generated Pull Request.
> 
> No, this is wrong. First you have to create the issue , then issue will be assigned. Then you have to work on it. Then create the PR, then your PR will merged.

Ok, I will do it that way.

**Review by khushi-purwar — APPROVED** [review]

**Pull request merged**
