### PR TITLE
Number System Converter

### LINKED ISSUE #700: Number System Converter
**Project title**

Number System Converter

**Project Description**

A web-app based Number System Converter
**Stack**:  

- [x] Html
- [x] CSS
- [x] JavaScript

### PR DESCRIPTION
**Pull request by AnIkeT126**
<hr>

A web app-based fully responsive Number System converter.

Fixes #700 

<hr>

## Type of change 📝

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Add a new project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Project using HTML, CSS & JS

<hr>
 
## Checklist ✅

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Optional) 📸

image

### CODE REVIEW

**Comment by AnIkeT126** [comment]
@gurjeetsinghvirdee This is a new PR, after merging the upstream as can be seen here 
image

Is it good to go now ??

**Comment by gurjeetsinghvirdee** [comment]
All ok but it converts base to base?

**Comment by AnIkeT126** [comment]
> All ok but it converts base to base?

from 2 to 10
10 to 2 etc

like different bases to different bases

**Comment by gurjeetsinghvirdee** [comment]
> > All ok but it converts base to base?
> 
> from 2 to 10 10 to 2 etc
> 
> like different bases to different bases

acha ok

**Review by khushi-purwar — APPROVED** [review]

**Pull request merged**
