### PR TITLE
Added CryptoRush Application

### LINKED ISSUE #69: A Crypto Currency Project
**Project title**
CryptoRush

**Project Description**
In this project user can view data related to about 100 crypto currencies in the world. It can be made using API and reactjs 

**Stack**:  
REACTJS
MATERIAL UI
API 
CSS

### PR DESCRIPTION
**Pull request by Abh1shekSingh**
I successfully added CryptoRush Application to the repo

<hr>

## Description 📜

Added CryptoRush Application by doing some changes and fixeing all the issue.

Fixes #69 

<hr>

## Type of change 📝

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [ ] Add a new project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [ ] Project using only HTML & CSS
- [ ] Project using HTML, CSS & JS
- [ ] Project using ReactJs

<hr>
 
## Checklist ✅

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Optional) 📸

Add the screenshot of the changes you have made

### CODE REVIEW

**Review by khushi-purwar — APPROVED** [review]

**Comment by Kushal997-das** [comment]
@khushi-purwar 
 Remove the tag as this one plagiarised .

https://github.com/surajm-333/Ace-The-FrontEnd/pull/69

**Comment by Abh1shekSingh** [comment]
> @khushi-purwar Remove the tag as this one plagiarised .
> 
> [surajm-333/Ace-The-FrontEnd#69](https://github.com/surajm-333/Ace-The-FrontEnd/pull/69)

bto i have already message Ace the frontend PA to close that PR from there. Why you are closing from here then ? it will delete only from one side as per instruction

**Comment by Kushal997-das** [comment]
> > @khushi-purwar Remove the tag as this one plagiarised .
> > [surajm-333/Ace-The-FrontEnd#69](https://github.com/surajm-333/Ace-The-FrontEnd/pull/69)
> 
> bto i have already message Ace the frontend PA to close that PR from there. Why you are closing from here then ? it will delete only from one side as per instruction

Because i found this PR already exits in others repo with the tag . Make sure they remove the tag and yeah one PR is allowed with the tag .

**Comment by Abh1shekSingh** [comment]
> > > @khushi-purwar Remove the tag as this one plagiarised .
> > > [surajm-333/Ace-The-FrontEnd#69](https://github.com/surajm-333/Ace-The-FrontEnd/pull/69)
> > 
> > 
> > bto i have already message Ace the frontend PA to close that PR from there. Why you are closing from here then ? it will delete only from one side as per instruction
> 
> Because i found this PR already exits in others repo with the tag . Make sure they remove the tag and yeah one PR is allowed with the tag .

one PR is marked as Invalid but another is marked with level only. 
As per instruction

**Comment by Abh1shekSingh** [comment]
Then 

> > > @khushi-purwar Remove the tag as this one plagiarised .
> > > [surajm-333/Ace-The-FrontEnd#69](https://github.com/surajm-333/Ace-The-FrontEnd/pull/69)
> > 
> > 
> > bto i have already message Ace the frontend PA to close that PR from there. Why you are closing from here then ? it will delete only from one side as per instruction
> 
> Because i found this PR already exits in others repo with the tag . Make sure they remove the tag and yeah one PR is allowed with the tag .

Then why are u removing the marks from both side

**Comment by Kushal997-das** [comment]
> Then
> 
> > > > @khushi-purwar Remove the tag as this one plagiarised .
> > > > [surajm-333/Ace-The-FrontEnd#69](https://github.com/surajm-333/Ace-The-FrontEnd/pull/69)
> > > 
> > > 
> > > bto i have already message Ace the frontend PA to close that PR from there. Why you are closing from here then ? it will delete only from one side as per instruction
> > 
> > 
> > Because i found this PR already exits in others repo with the tag . Make sure they remove the tag and yeah one PR is allowed with the tag .
> 
> Then why are u removing the marks from both side

They will remove from one side.

**Comment by Abh1shekSingh** [comment]
> > Then
> > > > > @khushi-purwar Remove the tag as this one plagiarised .
> > > > > [surajm-333/Ace-The-FrontEnd#69](https://github.com/surajm-333/Ace-The-FrontEnd/pull/69)
> > > > 
> > > > 
> > > > bto i have already message Ace the frontend PA to close that PR from there. Why you are closing from here then ? it will delete only from one side as per instruction
> > > 
> > > 
> > > Because i found this PR already exits in others repo with the tag . Make sure they remove the tag and yeah one PR is allowed with the tag .
> > 
> > 
> > Then why are u removing the marks from both side
> 
> They will remove from one side.

then make sure it get removed from one side only.

**Comment by Kushal997-das** [comment]
@Abh1shekSingh And you make sure we will never Spam again , I'll check everything one by one if i found any duplicate PR then your tag will be removed .

**Comment by Abh1shekSingh** [comment]
Listen bro, this PR was made on 1 march okay, i just kinda forget that i
already haave made it here. The gap between the two is huge

**Comment by Abh1shekSingh** [comment]
krle krle

**Comment by Abh1shekSingh** [comment]
> @Abh1shekSingh And you make sure we will never Spam again , I'll check everything one by one if i found any duplicate PR then your tag will be removed .

Listen bro, this PR was made on 1 march okay, i just kinda forget that i
already haave made it here. The gap between the two is huge @kushal997-das

**Comment by Abh1shekSingh** [comment]
@Kushal997-das  krle krle

**Pull request merged**
