### PR TITLE
Adding headlines project

### PR DESCRIPTION
**Pull request by abaran803**
This is PR regarding issue #7 . Please review this PR

### CODE REVIEW

**Comment by abaran803** [comment]
> This is PR regarding issue #7 . Please review this PR

Check this link: https://abaran803.github.io/WebDev-ProjectKart/Headlines/

**Comment by khushi-purwar** [comment]
@abaran803, I am  getting error after selecting country.
image

**Comment by abaran803** [comment]
> @abaran803, I am getting error after selecting country. image

This is b/c free plan of news api don't provide cors for live site, but for localhost do. Is there any news api with cors for live hosting for free?

**Comment by khushi-purwar** [comment]
Ok.  I will search any news API with cors.

**Comment by abaran803** [comment]
> Ok. I will search any news API with cors.

Ok

**Comment by abaran803** [comment]
> Ok. I will search any news API with cors.

Is it good to put a help wanted tag to this #8 so that others can help to find the news API, fit for this project?

**Comment by khushi-purwar** [comment]
> > Ok. I will search any news API with cors.
> 
> @khushi-purwar Is it good to put a help wanted tag to this #8 so that others can help to find the news API, fit for this project?

Correct the project description in readme file.

**Pull request merged**
