### PR TITLE
Twitter Login Page Clone 

### LINKED ISSUE #603: Twitter Clone
**Project title**
Twitter Clone 

**Project Description**
Twitter Clone using HTML5,CSS3,JS
**Stack**:  

- [X] Html
- [X] CSS
- [X] JavaScript

### PR DESCRIPTION
**Pull request by Mrjoy832**
<hr>

## Description 📜

Added Twitter Login Page Clone 
---
Fixes #603 

<hr>

## Type of change 📝

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [X] Add a new project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [X] Project using only HTML & CSS

<hr>
 
## Checklist ✅

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Optional) 📸

image

### CODE REVIEW

**Comment by Mrjoy832** [comment]
@khushi-purwar , Resolved conflicts

**Comment by Mrjoy832** [comment]
@khushi-purwar , Please check

**Review by gurjeetsinghvirdee — CHANGES_REQUESTED** [review]
your files changed into binary, better to make a new PR

**Comment by Mrjoy832** [comment]
> your files changed into binary, better to make a new PR

Okay

**Comment by Mrjoy832** [comment]
Resolved please check

**Comment by Mrjoy832** [comment]
> > Resolved please check
> 
> Jra wait kre, abhi soke uthe h krte h check

ha ha ..bud me vi koroge to chalega

**Comment by Mrjoy832** [comment]
@gurjeetsinghvirdee @khushi-purwar , changes are done...please check

**Comment by gurjeetsinghvirdee** [comment]
> @gurjeetsinghvirdee @khushi-purwar , changes are done...please check

Me filal apne conflicts thik kr ra hu jaise tere the, pta ni kha se aajate h daily🥲

**Comment by Mrjoy832** [comment]
> > @gurjeetsinghvirdee @khushi-purwar , changes are done...please check
> 
> Me filal apne conflicts thik kr ra hu jaise tere the, pta ni kha se aajate h daily🥲

yehi repo me ata hai sirf daily...bki o me think rahta hain

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Comment by Mrjoy832** [comment]
@gurjeetsinghvirdee  @khushi-purwar  please merge this

**Pull request merged**
