### PR TITLE
hysky website 

### PR DESCRIPTION
**Pull request by yash-25log**
## Description 📜

responsive website build
using html css js

This website can be used by any club in robotics
This mainly promotes any robotic teams service like a portfolio website

issue #964  solved

<hr />

## Domain of Contribution 📊

- [x] HTML, CSS, JS

<hr />
 
## Checklist ✅

- [x] I follow [Code of conduct](https://github.com/surajm-333/Ace-The-FrontEnd/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added required screenshot/gif depicting the working of the project in the folder
- [x] I am a GSSoC'22 contributor

<hr />

## Screenshots / Gif 📸
image
image
image

### CODE REVIEW

**Comment by yash-25log** [comment]
@khushi-purwar pls see to this pr

**Comment by yash-25log** [comment]
@gurjeetsinghvirdee

**Comment by yash-25log** [comment]
@gurjeetsinghvirdee

**Comment by yash-25log** [comment]
@gurjeetsinghvirdee

**Comment by gurjeetsinghvirdee** [comment]
> @gurjeetsinghvirdee

bhai exam me hu

**Comment by yash-25log** [comment]
> > @gurjeetsinghvirdee
> 
> bhai exam me hu

are to paper kr na lol

**Comment by yash-25log** [comment]
@gurjeetsinghvirdee bhai ab to krde merge leaderboard update se phele

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Comment by yash-25log** [comment]
@gurjeetsinghvirdee bhai #957 ko to level 3
merko level 2 y? 😭

**Comment by yash-25log** [comment]
@gurjeetsinghvirdee https://hysky-web.vercel.app/

**Pull request merged**
