### PR TITLE
Added Rock Paper Scissors Game

### LINKED ISSUE #179: Add Rock Paper Scissors Game
**Project title**
Rock Paper Scissors

**Project Description**
This webapp allows a user to play the conventional game of rock paper scissors against the computer and decides on the basis of user's move and computer's move, that who won or whether it was a tie round.

The game is available at : https://rajaditya28.github.io/Rock-Paper-Scissors/

**Screenshot**

Screenshot 2022-03-04 170358

**Stack**:  

- [x] Html
- [x] CSS
- [x] JavaScript

I would like to add this project. Please assign me the issue @khushi-purwar  @meinhoonharsh so I can get on it right away and make a PR as soon as possible.

### PR DESCRIPTION
**Pull request by rajaditya28**
<hr>

## Description 📜

I have added the Rock Paper Scissors game at 36th Position

Fixes #179 

<hr>

## Type of change 📝

- [x] Add a new project

<hr>

## Domain of Contribution 📊

- [x] Project using HTML, CSS & JS

<hr>
 
## Checklist ✅

- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Optional) 📸

Screenshot 2022-03-04 170358

### CODE REVIEW

**Review by khushi-purwar — APPROVED** [review]

**Review by khushi-purwar — CHANGES_REQUESTED** [review]
Resolve the conflicts at your end.

**Comment by rajaditya28** [comment]
> Resolve the conflicts at your end.

I have resolved the conflicts with the master branch. Kindly merge @khushi-purwar . 
Thank You !!

**Review by meinhoonharsh — APPROVED** [review]
RTC

**Comment by rajaditya28** [comment]
@khushi-purwar Please look into this PR when you get the time. Its ready to be merged I feel.

**Review by meinhoonharsh — APPROVED** [review]
@khushi-purwar You can Merge this PR

**Review by khushi-purwar — APPROVED** [review]

**Pull request merged**
