### PR TITLE
Added Hacker News ReactApp

### LINKED ISSUE #528: Want To Add Hacker News ReactApp
**Project title**
Hacker News

**Project Description**
A one place stop for every news that you want to read. It covers every topic you want to know about. Made using ReactJS and APIs integration

**Stack**:  

- [x] ReactJS

### PR DESCRIPTION
**Pull request by Abh1shekSingh**
<hr>

## Description 📜

Added Hacker News React App made using ReactJS and API integration.

Fixes #528 

<hr>

## Type of change 📝

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Add a new project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Project using ReactJs

<hr>
 
## Checklist ✅

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Optional) 📸

Add the screenshot of the changes you have made

hacker news

### CODE REVIEW

**Review by meinhoonharsh — CHANGES_REQUESTED** [review]
Seems a Reac App where `src/` is missing

**Comment by Abh1shekSingh** [comment]
Dont know how this thing happened lmao xd

**Review by khushi-purwar — APPROVED** [review]

**Comment by Abh1shekSingh** [comment]
@khushi these are the project clones that i have made with my own hardwork. and i think it should not come under copied content. why have you reduced the level. agar rerduce krna hi hai toh fer instagram clones, twiter clones jaise projects ka bhi krwayo

**Comment by khushi-purwar** [comment]
> @khushi these are the project clones that i have made with my own hardwork. and i think it should not come under copied content. why have you reduced the level. agar rerduce krna hi hai toh fer instagram clones, twiter clones jaise projects ka bhi krwayo

We ar changing the labels of all the PR's. It takes time to change all the labels of PR. Within 2-3 days, they will be changed

**Pull request merged**
