### PR TITLE
Flip Card Game

### LINKED ISSUE #858: Flip Card Game
**Project title**
Flip Card Game

**Project Description**
Create a Card containing the question and answer that you want to memorize.

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [] Html
- [] CSS
- [] JavaScript

Web capture_16-4-2022_134014_127 0 0 1

### PR DESCRIPTION
**Pull request by iamrahulmahato**
<hr>

## Description 📜

Create a Card containing the question and answer that you want to memorize.

Fixes #858

<hr>

## Type of change 📝

Please delete options that are not relevant. And in order to tick the check box just put x inside them for example [x] like this

- [] Add a new project
- [] Improve the readme of any project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant. And in order to tick the check box just put x inside them for example [x] like this

- [] Project using HTML, CSS & JS

<hr>
 
## Checklist ✅

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [] I have performed a self-review of my own code or work.
- [] I have commented on my code, particularly in hard-to-understand areas.
- [] My changes generates no new warnings.
- [] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Recommended) 📸
Web capture_2-5-2022_175752_127 0 0 1
Web capture_2-5-2022_175838_127 0 0 1

### CODE REVIEW

**Comment by iamrahulmahato** [comment]
Demo:

https://user-images.githubusercontent.com/49890655/166391031-0fc8d31f-b2eb-4a74-be64-3a503223991f.mp4

**Comment by gurjeetsinghvirdee** [comment]
@iamrahulmahato bro add some demo image so it looks good

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Comment by iamrahulmahato** [comment]
@gurjeetsinghvirdee bro are you taking about screenshots?

**Comment by gurjeetsinghvirdee** [comment]
> @gurjeetsinghvirdee bro are you taking about screenshots or background img at website
> 

Talking about flip cards use images so it looks good

**Comment by iamrahulmahato** [comment]
@gurjeetsinghvirdee bro added

**Comment by iamrahulmahato** [comment]
SS:
Web capture_2-5-2022_221757_127 0 0 1

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Pull request merged**
