### PR TITLE
GK FlipBook files added

### LINKED ISSUE #1427: General Knowledge Flip book
**Project title**
General Knowledge Flip book 

**Project Description**

General Knowledge digital  Flip book  made in html css
**Stack**:  

- [x] Html
- x[] CSS
- [x] JavaScript
-

### PR DESCRIPTION
**Pull request by RAHULBAWA777**
<hr>

## Description 📜

General knowledge digital flipbook ...happy learning:)
Fixes #1427 

<hr>

## Type of change 📝

- [x] Add a new project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant. In order to tick the check box just put x inside them for example [x] like this

- [x] Project using HTML, CSS & JS

<hr>
 
## Checklist ✅

Please delete options that are not relevant. In order to tick the check box just put x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Recommended) 📸

https://user-images.githubusercontent.com/91609324/167297209-aa2e202b-7705-428e-992c-720c2e4b9b2b.mp4

[README (2).md](https://github.com/khushi-purwar/WebDev-ProjectKart/files/8651733/README.2.md)

### CODE REVIEW

**Comment by Mrjoy832** [comment]
Add readme file

**Comment by RAHULBAWA777** [comment]
> Add readme file

done

**Comment by Mrjoy832** [comment]
> > Add readme file
> 
> done

image
where is readme?

**Comment by gurjeetsinghvirdee** [comment]
> image here

bhai aise ni kr, isko apne project folder ke andar daal readme.md file bna vha

**Pull request merged**
