### PR TITLE
Added Pronic Number Checker

### LINKED ISSUE #1188: Adding Pronic Number Checker
**Project title**
Pronic Number Checker

**Project Description**
A number is said to be a pronic number if the product of two consecutive integers is equal to the number. Example- 42 is said to be a pronic number, 42=6×7, here 6 and 7 are consecutive integers

**Stack**:  

- [x] Html
- [x] CSS
- [x] JavaScript

### PR DESCRIPTION
**Pull request by LiQuiD-404**
<hr>

## Description 📜

A simple JavaScript Project to check whether a number is a Pronic Number or not.

Fixes #1188 

<hr>

## Type of change 📝

- [x] Add a new project

<hr>

## Domain of Contribution 📊

- [x] Project using HTML, CSS & JS

<hr>
 
## Checklist ✅

- [x] I have performed a self-review of my own code or work.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshot
snip1
s / Gif (Recommended) 📸

### CODE REVIEW

**Comment by Mrjoy832** [comment]
Add Demo Video in readme and describe the topic

**Comment by LiQuiD-404** [comment]
@Mrjoy832 Added Demo Video. Kindly review

**Review by Mrjoy832 — APPROVED** [review]

**Comment by Mrjoy832** [comment]
giving label-2 for well structured readme

**Comment by LiQuiD-404** [comment]
> giving label-2 for well structured readme

Thank you so much. Made me emotional🥲

**Pull request merged**
