### PR TITLE
Added Food ordering Website(Fully Responsive)

### LINKED ISSUE #1406: Fully responsive food ordering website
**Project title**
Food Paradise

**Project Description**
I have created a template for fully responsive food ordering website. Please assign it to me @gurjeetsinghvirdee 

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

### PR DESCRIPTION
**Pull request by Areebah03**
Updated README.md
<hr>

## Description 📜

It is a fully responsive food ordering website. I have also created a menu page.

Fixes #1406 

<hr>

## Type of change 📝

- [x] Add a new project

<hr>

## Domain of Contribution 📊

- [x] Project using HTML, CSS & JS

<hr>
 
## Checklist ✅

- [x] I have performed a self-review of my own code or work.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
### Video

https://user-images.githubusercontent.com/85051124/167570788-c191f3d2-e7c3-45d8-9b01-4ed07073deaf.mp4
https://user-images.githubusercontent.com/85051124/167569668-aad3e164-efef-4836-a1d9-aa207fe1aedd.mp4

### CODE REVIEW

**Comment by gurjeetsinghvirdee** [comment]
Don't copy others content https://github.com/khushi-purwar/WebDev-ProjectKart/pull/826

**Comment by Areebah03** [comment]
I have not copied their content. This pr it plagiarised from https://www.youtube.com/watch?v=8KVrdL0VcAk&list=PLu0W_9lII9agiCUZYRsvtGTXdxkzPyItg&index=39&t=105s. I have taken help from online videos and tried to build it on my own.

**Comment by Areebah03** [comment]
@khushi-purwar @Mrjoy832 Please review my PR.

**Comment by Mrjoy832** [comment]
https://github.com/khushi-purwar/WebDev-ProjectKart/tree/master/Food%20ordering%20website 
already present..I cannot accept

**Comment by Mrjoy832** [comment]
## one Food-ordering site is already present ..and I haven't got any update from you...so sorry to say..but I am closing this

**Pull request closed without merging**
