### PR TITLE
CV Screener added

### LINKED ISSUE #360: CV Screener web app
**Project title**
CV Screener web app

**Project Description**
A simple CV screener webapp used for viewing CVs.

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

### PR DESCRIPTION
**Pull request by Manik-Aggarwal**
<hr>

## Description 📜

A CV Screener web app used to screen the CVs.

Fixes #360

<hr>

## Type of change 📝

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Add a new project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Project using only HTML & CSS
- [x] Project using HTML, CSS & JS

<hr>
 
## Checklist ✅

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Optional) 📸

Add the screenshot of the changes you have made

### CODE REVIEW

**Comment by Manik-Aggarwal** [comment]
@khushi-purwar pls review this PR and add gssoc label

**Review by khushi-purwar — CHANGES_REQUESTED** [review]
Please add the readme file also.

**Comment by Manik-Aggarwal** [comment]
Ok I will add it

**Comment by khushi-purwar** [comment]
Kindly add the Readme file asap, so that the PR gets successfully merged.

**Comment by Manik-Aggarwal** [comment]
Readme added @khushi-purwar

**Review by khushi-purwar — APPROVED** [review]

**Pull request merged**
