### PR TITLE
adding digital clock, resolving issue #756

### LINKED ISSUE #756: DIGITAL CLOCK
**Project title**

DIGITAL CLOCK

**Project Description**

A web-app based Digital Clock.

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

### PR DESCRIPTION
**Pull request by AnIkeT126**
<hr>

## Description 📜

A web app Based Digital Clock

Fixes #756 

<hr>

## Type of change 📝

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Add a new project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Project using HTML, CSS & JS

<hr>
 
## Checklist ✅

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [ x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Optional) 📸

image

### CODE REVIEW

**Comment by AnIkeT126** [comment]
@khushi-purwar please merge this PR, upon reviewing it.

**Comment by AnIkeT126** [comment]
@khushi-purwar please merge this PR, upon reviewing it.

**Comment by AnIkeT126** [comment]
@khushi-purwar Can you please review this PR and merge it upon finding it correct.

**Comment by gurjeetsinghvirdee** [comment]
I'm closing this PR this project already in our repo

**Pull request closed without merging**
