### PR TITLE
To Do App

### LINKED ISSUE #453: Add an To-Do App
**Project title**
To-Do App 

**Project Description**
This is a to-do app made using HTML , CSS and Javascript to list day to day tasks and cross them out after it gets done .

**Stack**:  

- [x] Html
- [x] CSS
- [x] JavaScript

**App UI**

Screenshot (667)

@khushi-purwar Kindly assign me the above issue .

### PR DESCRIPTION
**Pull request by MannyP31**
<hr>

## Description 📜

Fixes #453 

<hr>

## Type of change 📝

- [x] Add a new project

<hr>

## Domain of Contribution 📊

- [x] Project using HTML, CSS & JS

<hr>
 
## Checklist ✅

- [x] I have performed a self-review of my own code or work.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I'm GSSoC'22 contributor

### CODE REVIEW

**Review by gurjeetsinghvirdee — CHANGES_REQUESTED** [review]
can you replace `background image` with `background color` it looks much better

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Comment by MannyP31** [comment]
Hey @gurjeetsinghvirdee I have done the necessary changes . Kindly look into it .

**Comment by gurjeetsinghvirdee** [comment]
> Hey @gurjeetsinghvirdee I have done the necessary changes . Kindly look into it .

yeah I saw and merged it

**Comment by MannyP31** [comment]
Thnks a lot

**Pull request merged**
