### PR TITLE
Added Dice Game

### LINKED ISSUE #506: Adding a Dice Game
**Project title**
Adding a Dice Game

**Project Description**
I will make this game using HTML, CSS, JS

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

### PR DESCRIPTION
**Pull request by TG922**
<hr>

## Description 📜

- Added Dice Game
- Dice game developed using HTML, CSS, JS.
- This game is an alternate version of a dice game developed with web tech.

Fixes #506 

<hr>

## Type of change 📝

- [x] Add a new project

<hr>

## Domain of Contribution 📊

- [x] Project using HTML, CSS & JS

<hr>
 
## Checklist ✅

- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Optional) 📸

Image76

### CODE REVIEW

**Comment by TG922** [comment]
@khushi-purwar I want to suggest something, Don't add a level 3 label to those projects who haven't used javascript !!



> Only the readme file is pushed. No HTML, no CSS file is there. Please check at your end.

Ok I will check that

**Comment by gurjeetsinghvirdee** [comment]
@TG922 add other files either I will close this issue

**Review by gurjeetsinghvirdee — CHANGES_REQUESTED** [review]
add other files @TG922 either I have to close this PR

**Comment by TG922** [comment]
Ok will do today ASAP @gurjeetsinghvirdee

**Pull request closed without merging**
