### PR TITLE
adding hotel booking app

### LINKED ISSUE #898: Hotel Booking App
**Project title**

Hotel Booking App

**Project Description**

A web app for hotel booking.

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript
- [x] ReactJS

### PR DESCRIPTION
**Pull request by AnIkeT126**
## Description

A fully responsive web app for hotel booking.

Please include a summary of the change and which issue is fixed. 

Fixes #898 

<hr>

## Type of change 📝

Please delete options that are not relevant. And in order to tick the check box just put x inside them for example [x] like this

- [x] Add a new project

## Domain of Contribution 📊

- [x] Project using ReactJs

<hr>
 
## Checklist ✅

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Recommended) 📸

image

### CODE REVIEW

**Comment by AnIkeT126** [comment]
@gurjeetsinghvirdee please review this PR.

**Comment by AnIkeT126** [comment]
@khushi-purwar and @gurjeetsinghvirdee please review this PR, and merge it upon finding it correct.

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Comment by AnIkeT126** [comment]
@gurjeetsinghvirdee what kind of projects will get a level 3 label, in general, I am asking as this was a responsive project made from react.

**Comment by gurjeetsinghvirdee** [comment]
I think you have to deploy so we can check them 
It's an simple way to check aproject 

If you add pic how can we know how it's work

Better to deploy and add link in readme file

**Comment by AnIkeT126** [comment]
Ok, can I do it now??

**Comment by AnIkeT126** [comment]
> I think you have to deploy so we can check them It's an simple way to check aproject
> 
> If you add pic how can we know how it's work
> 
> Better to deploy and add link in readme file

Can i do it now??

**Comment by gurjeetsinghvirdee** [comment]
Ok

**Pull request merged**
