### PR TITLE
Added Theme Builder

### LINKED ISSUE #778: Cutom Theme Builder
**Project title**
Theme Builder

**Project Description**
For a Developer and designer chossing the best theme is always a hard task. Theme builder is the website, where you can make custom theme of your own choice for your web and android application

**Stack**:  
- [x] ReactJS

### PR DESCRIPTION
**Pull request by Abh1shekSingh**
<hr>

## Description 📜

Theme Builder is a website where you can make your custom theme for web and android design. As it is The most difficult task for developer and designers

Fixes #778 

<hr>

## Type of change 📝

- [x] Add a new project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Project using ReactJs

<hr>
 
## Checklist ✅

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Optional) 📸

theme builder
theme1

### CODE REVIEW

**Comment by Abh1shekSingh** [comment]
@khushi-purwar @meinhoonharsh  Please Review this PR of Mine

**Comment by gurjeetsinghvirdee** [comment]
This one also?
[Theme builder](https://theme-builder.netlify.app/)
[Atapas repo](https://github.com/atapas/theme-builder)

**Comment by gurjeetsinghvirdee** [comment]
> Bro the main thing, I am not copying pasting the code. It's something that comes under cloning. I am first learning how to make then making cloning. And I think that should not be invalid

Ok not invid but comes under plag bcoz the code was same, lemme ask PM

**Comment by Abh1shekSingh** [comment]
@what is this dude. I have told you earlier gain you had done the dame thing ? What is you real issue, Are you afraid to compete  >

**Pull request merged**
