### PR TITLE
Sound Classifier added

### LINKED ISSUE #1201: Sound Classifier Web App
**Project title**
Sound Classifier

**Project Description**
(Describe the project over here)
It takes input from microphone and then predicts when the user has spoken into words

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] CSS
- [x] ReactJS

### PR DESCRIPTION
**Pull request by shreya024**
<hr>

## Description 📜
Added sound classifier react app
Fixes #1201

<hr>

## Type of change 📝

Please delete options that are not relevant. In order to tick the check box just put x inside them for example [x] like this

- [x] Add a new project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant. In order to tick the check box just put x inside them for example [x] like this

- [x] Project using ReactJs

<hr>
 
## Checklist ✅

Please delete options that are not relevant. In order to tick the check box just put x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Recommended) 📸

image
image

### CODE REVIEW

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Comment by gurjeetsinghvirdee** [comment]
@shreya024 is it responsive?

**Comment by shreya024** [comment]
> @shreya024 is it responsive?

It is responsive.And I made it in React ,would be great if you would give it a level3

**Comment by gurjeetsinghvirdee** [comment]
> > @shreya024 is it responsive?
> 
> It is responsive.And I made it in React ,would be great if you would give it a level3

yeah that's y I ask

**Comment by shreya024** [comment]
> > > @shreya024 is it responsive?
> > 
> > 
> > It is responsive.And I made it in React ,would be great if you would give it a level3
> 
> yeah that's y I ask

Thank you :)

**Pull request merged**
