### PR TITLE
Added clone of JetBrains Website

### PR DESCRIPTION
**Pull request by eswarbhageerath**
This is the PR of the issue JetBrains Website Clone #948..please review it sir

### CODE REVIEW

**Review by gurjeetsinghvirdee — CHANGES_REQUESTED** [review]
bro remove Hacker Earth project files & I've a doubt that you don't make this project

**Comment by eswarbhageerath** [comment]
@gurjeetsinghvirdee  Sir, as I am new in creating multiple PRs in same repo, I am unable to make it perfectly , so the files of hacker earth and jet brains have been mixed up..sorry for all the mess...I have been working on this since long time in front end development and UI designs, I made this project by my own/...please review my PR sir

**Comment by eswarbhageerath** [comment]
@khushi-purwar Please review my PR

**Comment by gurjeetsinghvirdee** [comment]
> @khushi-purwar Please review my PR

Exam khtm krlu fir aata hu

**Comment by gurjeetsinghvirdee** [comment]
@eswarbhageerath that's not fair bro that you are copying code from the original website

Screenshot (895)


Screenshot (896)

**Comment by eswarbhageerath** [comment]
@gurjeetsinghvirdee I am not Copying the code..Those projects are already made by me as a part of College academics

**Comment by gurjeetsinghvirdee** [comment]
> @gurjeetsinghvirdee I am not Copying the code..Those projects are already made by me as a part of College academics

You have any proof bcoz these code exactly looks like same to same from official website

**Pull request closed without merging**
