### PR TITLE
Scratch Card Application🧩

### LINKED ISSUE #847: Scratch Card Application🧩
**Project title**
Scratch Card Application🧩

**Project Description**
I want to add Scratch Card Application🧩 like Gpay/Paytm scratch Cards using HTML,CSS,JS

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [X] Html
- [X] CSS
- [X] JavaScript

### PR DESCRIPTION
**Pull request by Mrjoy832**
<hr>

## Description 📜

It's typical Scratch Card Application which everyone can see  in any payment applications mainly in Gpay, Paytm..which is made by HTML,CSS,JS. Where By cursor when we rub the card any random surprise will be appeared.

Fixes #847 

<hr>

## Type of change 📝

- [x] Add a new project

<hr>

## Domain of Contribution 📊

- [x] Project using HTML, CSS & JS

<hr>
 
## Checklist ✅

- [x] I have performed a self-review of my own code or work.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Recommended) 📸

https://user-images.githubusercontent.com/77873383/164383920-29cb1887-0ef0-43d1-9afa-c5e1e70d82ef.mp4

### CODE REVIEW

**Comment by Mrjoy832** [comment]
@khushi-purwar  please check it

**Comment by gurjeetsinghvirdee** [comment]
Bs scratch hoga paise bhi dalwa deta kamai hojati

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Comment by gurjeetsinghvirdee** [comment]
@Mrjoy832 conflicts h jra dekh lena

**Comment by Mrjoy832** [comment]
> @Mrjoy832 conflicts h jra dekh lena

Pr create ke time nehi rehta.. suddenly bud me kyese ho jata hain pata nehi

**Comment by gurjeetsinghvirdee** [comment]
> > @Mrjoy832 conflicts h jra dekh lena
> 
> Pr create ke time nehi rehta.. suddenly bud me kyese ho jata hain pata nehi

bhut sari PR merge hone pr aajata hai

**Comment by Mrjoy832** [comment]
> > > @Mrjoy832 conflicts h jra dekh lena
> > 
> > 
> > Pr create ke time nehi rehta.. suddenly bud me kyese ho jata hain pata nehi
> 
> bhut sari PR merge hone pr aajata hai

achaa

**Comment by Mrjoy832** [comment]
> > > > @Mrjoy832 conflicts h jra dekh lena
> > > 
> > > 
> > > Pr create ke time nehi rehta.. suddenly bud me kyese ho jata hain pata nehi
> > 
> > 
> > bhut sari PR merge hone pr aajata hai
> 
> achaa

Resolved Conflicts

> @Mrjoy832 conflicts h jra dekh lena

@gurjeetsinghvirdee Resolved Conflicts

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Pull request merged**
