### PR TITLE
Added New Year countdown project

### LINKED ISSUE #655: I want to add a New year countdown project to the web dev projectKart repository
**Project title**
(New Year Countdown)

**Project Description**
Hey project admin I'm a GSSOC participant and I have come up with your project and I would love to contribute to your project one more time I want to add a New year countdown project it is a very basic project for beginners who don't know how to work with dates and DOM it can give them an idea of how things work so I hope that you will go through my issue and assign me this issue to work on...

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

New Year Countdown - Google Chrome 10-04-2022 12 24 49 PM

### PR DESCRIPTION
**Pull request by AmolShelke2**
<hr>

## Description 📜

I have added a new project to the current repository it is a new year countdown created with HTML CSS and JavaScript my changes generate no issues so you can go through it and I hope that you will merge my pull request 

Fixes #655

<hr>

## Type of change 📝

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Add a new project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x ] Project using HTML, CSS & JS
<hr>
 
## Checklist ✅

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Optional) 📸

Add the screenshot of the changes you have made
New Year Countdown - Google Chrome 10-04-2022 12 24 49 PM

### CODE REVIEW

**Comment by AmolShelke2** [comment]
Hey @khushi-purwar please review this PR

**Review by gurjeetsinghvirdee — APPROVED** [review]
Looks good

**Review by khushi-purwar — APPROVED** [review]

**Comment by AmolShelke2** [comment]
@gurjeetsinghvirdee Hey bro why you remove the level 3 label with level 1🥲

**Comment by gurjeetsinghvirdee** [comment]
> @gurjeetsinghvirdee Hey bro why you remove the level 3 label with level 1🥲

I can't reply each and everyone for this


"The *quality* of PR decides the level. Labels on issues don't matter."

**Comment by AmolShelke2** [comment]
Ohhh i have seen many people who are copying others code and creating pr
and they are getting level 3 labels..
And project admins are not even adding the GSSOC labels on my issues and
pull request.

**Comment by gurjeetsinghvirdee** [comment]
I don't know about before bcoz I joined this project 2-3 days before by the way All merged PR will be check from today onwards

**Comment by gurjeetsinghvirdee** [comment]
I don't know about before bcoz I joined this project 2-3 days before by the way All merged PR will be check from today onwards

**Comment by gurjeetsinghvirdee** [comment]
I don't know about before bcoz I joined this project 2-3 days before by the way All merged PR will be check from today onwards

**Comment by gurjeetsinghvirdee** [comment]
Thankyou @anamansari062

**Pull request merged**
