### PR TITLE
Update style.css

### LINKED ISSUE #1181: Css Improve in #1170
**Project title**
 CSS Improve in #1170 

**Project Description**

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] CSS

### PR DESCRIPTION
**Pull request by AnIkeT126**
<hr>

## Description 📜

updated style.css for #1144 and made UI interactive and responsive.

Fixes #1181 

<hr>

## Type of change 📝

Please delete options that are not relevant. In order to tick the check box just put x inside them for example [x] like this

- [x] Modified or enhanced the existing projects

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant. In order to tick the check box just put x inside them for example [x] like this

- [x] Project using only HTML & CSS

<hr>
 
## Checklist ✅

Please delete options that are not relevant. In order to tick the check box just put x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Recommended) 📸

image

### CODE REVIEW

**Comment by AnIkeT126** [comment]
@gurjeetsinghvirdee please review this PR.

**Review by khushi-purwar — APPROVED** [review]

**Comment by khushi-purwar** [comment]
Please change the gradient.

**Comment by AnIkeT126** [comment]
> Please change the gradient.

to what colors???

**Comment by gurjeetsinghvirdee** [comment]
> > Please change the gradient.
> 
> to what colors???

gradient

**Comment by AnIkeT126** [comment]
image
is this fine??

**Comment by gurjeetsinghvirdee** [comment]
> image is this fine??

hn shi h

**Comment by AnIkeT126** [comment]
> > image is this fine??
> 
> hn shi h

change kr diya and ise responsive bhi kr diya hai...

**Pull request merged**
