### PR TITLE
videoBackground  (added Readme)

### LINKED ISSUE #1691: video Background Scroll
**Project title**
Scroll Video

**Project Description**
(Describe the project over here)

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript
- [] ReactJS
image
----
image
----
image

### PR DESCRIPTION
**Pull request by DragonUncaged**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. 

Fixes #1691 

<hr>

## Type of change 📝

Please delete options that are not relevant. In order to tick the check box just put x inside them for example [x] like this

- [x] Add a new project
- [] Modified or enhanced the existing projects
- [] Improve the readme of any project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant. In order to tick the check box just put x inside them for example [x] like this

- [] Project using only HTML & CSS
- [x] Project using HTML, CSS & JS
- [] Project using ReactJs

<hr>
 
## Checklist ✅

Please delete options that are not relevant. In order to tick the check box just put x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Recommended) 📸
image

### CODE REVIEW

**Comment by Mrjoy832** [comment]
Readme is not here...add working video

**Comment by DragonUncaged** [comment]
> Readme is not here...add working video

done!!

**Comment by Mrjoy832** [comment]
@DragonUncaged getting DM's on discord  about Plagarism content in your previous PR's ...be aware😶

**Comment by DragonUncaged** [comment]
> @DragonUncaged getting DM's on discord about Plagarism content in your previous PR's ...be aware😶

👍

**Comment by Mrjoy832** [comment]
# copied from 🙂
https://www.youtube.com/watch?v=gDMa3xJ6xqg

**Pull request closed without merging**
