### PR TITLE
Add News Website

### LINKED ISSUE #159: Add a News Website
**Project title**
News Website

**Project Description**
This is a News website using news API.

- [x] Html
- [x] CSS
- [x] JavaScript
Please assign me.

### PR DESCRIPTION
**Pull request by Aritra777**
## Type of change 📝
- [x] Add a new project
<hr>

Fixes #159 

## Domain of Contribution 📊
- [x] Project using HTML, CSS & JS
<hr>
 
## Checklist ✅
- [x] My changes generates no new warnings.
- [x] I'm GSSoC'22 contributor

### CODE REVIEW

**Comment by khushi-purwar** [comment]
Please mention the issue number

**Comment by khushi-purwar** [comment]
Resolve the conflicts at your end

**Comment by khushi-purwar** [comment]
Kindly mention the issue number

**Comment by Aritra777** [comment]
My issue no. is #159

**Review by meinhoonharsh — CHANGES_REQUESTED** [review]
Just add a Readme for this Project and it is perfect to get merged

**Comment by Aritra777** [comment]
@meinhoonharsh I have added the readme. Kindly check that.

**Review by khushi-purwar — APPROVED** [review]

**Pull request merged**
