### PR TITLE
adding custom color picker

### LINKED ISSUE #703: Color-Choosing Game
**Project title**

Color-Choosing Game

**Project Description**

A web-app based Color-Choosing Game

**Stack**:  

- [x] Html
- [x] CSS
- [x] JavaScript

### PR DESCRIPTION
**Pull request by AnIkeT126**
<hr>

## Description 📜

A web-app based Color-Choosing Game

Fixes #703 

<hr>

## Type of change 📝

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Add a new project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Project using HTML, CSS & JS

<hr>
 
## Checklist ✅

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Optional) 📸

image

### CODE REVIEW

**Comment by AnIkeT126** [comment]
@khushi-purwar please merge this PR, upon reviewing it.

**Comment by AnIkeT126** [comment]
@khushi-purwar please merge this PR, upon reviewing it.

**Comment by AnIkeT126** [comment]
@khushi-purwar Can you please review this PR and merge it upon finding it correct.

**Review by gurjeetsinghvirdee — CHANGES_REQUESTED** [review]
This branch is 1 commit ahead, 187 commits behind khushi-purwar/WebDev-ProjectKart:master.

**Comment by AnIkeT126** [comment]
> This branch is 1 commit ahead, 187 commits behind khushi-purwar/WebDev-ProjectKart:master.

This branch is one commit ahead because of its own commit and when I made this PR, the branch was fully fetched and merged.
So please approve this PR, as that is because of the delay in approval and merge

**Comment by AnIkeT126** [comment]
@khushi-purwar and @gurjeetsinghvirdee when I was assigned this issue i was given a level label 3 as my other issues and PR, it seems that you have removed those to ass new, please understand that we worked on these issues considering the amount of points we were getting, so please restore my old level lables in all the PRs because I started working on them post the level label was addressed. 

> > This branch is 1 commit ahead, 187 commits behind khushi-purwar/WebDev-ProjectKart:master.
> 


@khushi-purwar and @gurjeetsinghvirdee This branch is one commit ahead because of its own commit and when I made this PR, the branch was fully fetched and merged. So please approve this PR, as that is because of the delay in approval and merge

**Comment by AnIkeT126** [comment]
@khushi-purwar can you review this PR now, and please merge it with its original level label.

**Comment by AnIkeT126** [comment]
@gurjeetsinghvirdee and @khushi-purwar I fetched upstream and merged into this branch. Can you once check this too

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Review by khushi-purwar — APPROVED** [review]

**Pull request merged**
