### PR TITLE
Svg animation effect

### LINKED ISSUE #1673: SVG-animation-effect-not-working
**Project Name**
SVG-animation-effect

**Project link**

https://github.com/khushi-purwar/WebDev-ProjectKart/tree/master/SVG%20animation%20effect

you can check also, this project doesn't have any kind of svg animation , only a static svg is there, I want to add my own svg animation which It is very cool .

assign me this issue under gssoc22

### PR DESCRIPTION
**Pull request by mayank-del**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. 

Fixes #1673 

<hr>

## Type of change 📝

Please delete options that are not relevant. In order to tick the check box just put x inside them for example [x] like this

- [] Add a new project
- [] Modified or enhanced the existing projects
- [] Improve the readme of any project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant. In order to tick the check box just put x inside them for example [x] like this

- [] Project using only HTML & CSS
- [] Project using HTML, CSS & JS
- [] Project using ReactJs

<hr>
 
## Checklist ✅

Please delete options that are not relevant. In order to tick the check box just put x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] My changes generate no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Recommended) 📸

ezgif-4-a7cc38b3a6

### CODE REVIEW

**Comment by mayank-del** [comment]
@Gurdeep475 , @Mrjoy832 , please check and merge, else seven days will be over and bot will close my issue.

**Comment by Mrjoy832** [comment]
image
plag hain sayed?😏😏

**Comment by Mrjoy832** [comment]
image

**Comment by mayank-del** [comment]
> image plag hain sayed?😏😏

@Mrjoy832 , image is taken from undraw.io which open source, they use to say that anyone can use their svg in his project and   i did screen recording from bandicam app, that's why their watermark is  present over there.

**Comment by mayank-del** [comment]
> image

@Mrjoy832 , all these projects are mine, that's why they are coming together.

**Comment by Mrjoy832** [comment]
> 1. Add readme
> 2. Put Working Demo Video of Your own
> 3. insert deployed Link of Your own Github Pages into readme

4. Fix why 12 files are changed

**Comment by mayank-del** [comment]
@Mrjoy832  please merge pr #1651 , it was first PR, then I will it will no longer come as change

**Comment by mayank-del** [comment]
@Mrjoy832 sir , I did whatever you told , I removed every unwanted files . now  merge it.

**Comment by mayank-del** [comment]
@Mrjoy832 , @Gurdeep475 sir , please remove invalid  label, you added that just because you thought that image i have stolen from somewhere , but let me tell you, I downloaded this svg from undraw.io where it is clearly written that anyone can download it and use it in their project, after that , i used figma to modify my svg  in the way , i require for my project, i am ensuring you , if you get any such animation then you can remove this pr. but please trust me , I can make the entire animation in front you live in discord. so, please merge it.

**Comment by mayank-del** [comment]
> @Mrjoy832 , @Gurdeep475 sir , please remove invalid label, you added that just because you thought that image i have stolen from somewhere , but let me tell you, I downloaded this svg from undraw.io where it is clearly written that anyone can download it and use it in their project, after that , i used figma to modify my svg in the way , i require for my project, i am ensuring you , if you get any such animation on internet then you can remove this pr. but please trust me , I can make the entire animation in front you live in discord. so, please merge it.

@Mrjoy832 , are you there??

**Comment by Mrjoy832** [comment]
image
You have deleted all contents from to-do , now If I Merge it then to-do files will be deleted.
**Better You Clone this repo in another location of LOcal machine and make a fresh PR , mentioning this same issue, then this problem will not occur**

**Comment by mayank-del** [comment]
> image You have deleted all contents from to-do , now If I Merge it then to-do files will be deleted. **Better You Clone this repo in another location of Local machine and make a fresh PR , mentioning this same issue, then this problem will not occur**

but you have closed acceptance of new pr. So, just do one thing , I am pasting your old todo app in those changes and then you can merge it

**Comment by mayank-del** [comment]
@Mrjoy832 , It also do not have any conflict with main

**Comment by Mrjoy832** [comment]
## You have 3 PR's with same problems...close these 3 ....delete local repo...clone again make fresh 3 pr's without any problem again...dm me on discord...I will merge🤗

**Comment by mayank-del** [comment]
> ## You have 3 PR's with same problems...close these 3 ....delete local repo...clone again make fresh 3 pr's without any problem again...dm me on discord...I will merge🤗

Give me Discord ID  first

**Comment by Mrjoy832** [comment]
> > ## You have 3 PR's with same problems...close these 3 ....delete local repo...clone again make fresh 3 pr's without any problem again...dm me on discord...I will merge🤗
> 
> Give me Discord ID first

MrJOY#6245

**Comment by Mrjoy832** [comment]
# merged fresh one

**Pull request closed without merging**
