### PR TITLE
Added Virtual Keyboard 

### LINKED ISSUE #1037: Building a virtual keyboard with JS
**Virtual Keyboard**

**Project Description**
I want to add a virtual keyboard to the repo, I plan to use Vanilla JS, CSS, and HTML for this project. I think this will be a good and unique learning experience for beginners to learn JS DOM and HTML. I plan to add minimal design to the project.

**Stack**:  

- [X] Html
- [X] CSS
- [X] JavaScript

### PR DESCRIPTION
**Pull request by MonarchGitHub**
<hr>

## Description 📜

I have added a Virtual Keyboard created with HTML and JS to the repository.
closes #1037 

<hr>

## Type of change 📝

- [x] Add a new project

<hr>

## Domain of Contribution 📊

- [x] Project using HTML, CSS & JS

<hr>
 
## Checklist ✅

Please delete options that are not relevant. In order to tick the check box just put x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots

image

### CODE REVIEW

**Review by gurjeetsinghvirdee — CHANGES_REQUESTED** [review]
Attach a video to readme file & change the keyboard color it doesn't look good

**Comment by MonarchGitHub** [comment]
@gurjeetsinghvirdee should I go with light colors or dark ones for the keyboard?

**Comment by gurjeetsinghvirdee** [comment]
> @gurjeetsinghvirdee should I go with light colors or dark ones for the keyboard?

Little bit more dark so keywords color will be visible

**Comment by MonarchGitHub** [comment]
ok got it 👍

**Comment by MonarchGitHub** [comment]
@gurjeetsinghvirdee I have added the video to the readme and updated the keyboard color. Kindly add level tags and review the PR 😃

**Comment by gurjeetsinghvirdee** [comment]
> @gurjeetsinghvirdee I have added the video to the readme and updated the keyboard color. Kindly add level tags and review the PR 😃 

Will do tomorrow, I have a busy schedule today

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Comment by MonarchGitHub** [comment]
@gurjeetsinghvirdee the level tag assigned was Level 3 in #1037, kindly fix the level tag in PR

**Comment by gurjeetsinghvirdee** [comment]
> @gurjeetsinghvirdee the level tag assigned was Level 3 in #1037, kindly fix the level tag in PR

bro Level3 PR ni hai ye, PR labels difficulty ko dekh ke set hoti hai Issue Labels ki value ni h

**Comment by MonarchGitHub** [comment]
> > @gurjeetsinghvirdee the level tag assigned was Level 3 in #1037, kindly fix the level tag in PR
> 
> bro Level3 PR ni hai ye, PR labels difficulty ko dekh ke set hoti hai Issue Labels ki value ni h

Okay got it 👍

**Pull request merged**
