### PR TITLE
Added expense Tracker

### LINKED ISSUE #467: Expense Tracker
**Project title**
Expense Tracker ( Functioning)
**Project Description**
It is a dynamically working expense tracker that can be used to track how much we are spending and adding  to the wallet
**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

### PR DESCRIPTION
**Pull request by RajAdwaita**
<hr>

## Description 📜

Added a Expense Tracker built using html cs and js.

Fixes #467 

<hr>

## Type of change 📝

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Add a new project

<hr>

## Domain of Contribution 📊

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] Project using HTML, CSS & JS

<hr>
 
## Checklist ✅

Please delete options that are not relevant.And in order to tick the check box just but x inside them for example [x] like this

- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I'm GSSoC'22 contributor

<hr>
 
## Screenshots / Gif (Optional) 📸

Add the screenshot of the changes you have made

### CODE REVIEW

**Review by meinhoonharsh — CHANGES_REQUESTED** [review]
Would be great If you can add Screenshot/GIF or any live preview link for the app

and make sure to add Readme also

**Comment by RajAdwaita** [comment]
Sure will do it

**Comment by RajAdwaita** [comment]
Screenshot 2022-04-04 195454

**Comment by RajAdwaita** [comment]
I have also added the README file

**Comment by RajAdwaita** [comment]
https://lucky-croquembouche-c13668.netlify.app/

**Review by khushi-purwar — APPROVED** [review]

**Pull request merged**
